marshmallow-insurance/smores-react

src/Icon/Icon.tsx

Add new icons for the Cancellation Page
- Icons for car on its side
- Icon for refunds
- Icon for charges
etc.)

Add new icons for the Cancellation Page

---

src/Dropdown/Dropdown.stories.js
src/Dropdown/Dropdown.tsx

Ensure the dropdown resets to initial state, when the dropdown changes. Previously, if the user selected item 3 in the list, then the list changes, item 3 will still be selected even though the value and label has completely changed, because it's a new list.
The dropdown control used in Agent Portal and Customer Account

Reset dropdown when the list changes

---

.prettierrc

This is a proposal to update Prettier config and update the config to add spaces around arguments inside brackets (sensible whitespace) and remove semi-colons (as the compiler will add these on build when minimised).
- Remove reference to config options that are the `default` for Prettier
- Set `"bracketSpacing": true` to add spacing around arguments
- Set `"semi": false,` to remove semi-colons

Proposal: update Prettier config and update options

---

.eslintrc
src/utils/measure.tsx

Add missing semicolons to measure util used by the `Box` component. Without you can't use two properties together.
- Measure util
- Box component

Fix: add missing semicolons to measure util

---

README.md
package-lock.json
package.json

I've basically broken the signup-flow by migrating to react 17 there to keep up with create-react-app.
And since this one is bringing in react 16.x it's conflicting. As I guess we'd want to update it everywhere anyway this can be a start.
To me that also bring the question if all the "dependencies" in there should be peerDependencies but that might need further change in setup so let's maybe keep it for later.
(I've also moved snyk as it's most likely just a dev dependency, right?)
Can you also remind me if anything specific would be needed to have it released or just need to merge it?

Upgrade react version to 17.0.1

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

This does not change any rendering, but avoids console errors due to passing children into a Text container (cannot nest a `<div>` in a `<p>` tag, etc.
- Modal

Changed modal children container to box

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

As mentioned with @habin-isa, changed position of Modal overlay to `fixed` to avoid width being set by the Wrapper component in the Router in customer-portal-www. Also added `z-index: 999` to overlay to show above the header.
- Modal

position fixed for modal overlay

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

from: 
to:
Fixed flex direction on Modal

changed flex direciton to column in Modal

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

Modal width can now be set with an optional prop. This enables refactoring the old Modal in customer-portal-www.
- Modal

added width prop to modal for refactoring

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

From:
To:
Changes the height of the modal to hug the bottom of the screen for better usability.
- Modal component

modified height of modal drawer

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

Currently Modals will show by default, as the variable to show/hide is ignored by setting display twice.

🐛 removed hardcoded flex from modal

---

src/Button/Button.tsx

To stop the icon getting squashed for bigger sized icons, request from Matt

Changes to margin

---

src/Button/Button.tsx

Adding flex grow 1 to children of button so that the the icon is kept to the left and text is centred, at Jason's request
- Buttons buttons butttons

Add flex grow to children container button

---

src/Datepicker/Datepicker.stories.js
src/Datepicker/Datepicker.tsx

- Added optional Props to DatePicker to disable picking weekends, and to shift the days along correctly (like a calendar). Shifting the days is necessary as otherwise weekends are in the middle sometimes (looks very odd)
- caret icons aren't displaying properly without adding !important to the padding on the styling here.
**I think shifting the days along correctly would be nice to have by default, but didn't want to break any existing layouts**
- Date Picker

Date picker shift days ignore weekends

---

src/Button/Button.tsx

Added border to primary buttons so the are the same size as the others.
Now if you have a primary and a secondary button side by side, the secondary it's 4px taller because of the border.

Fixed Buttons height size

---

src/Emoji/Emoji.stories.js
src/Emoji/Emoji.tsx
src/Emoji/README.md
src/Emoji/__tests__/Emoji.js
src/Emoji/__tests__/__snapshots__/Emoji.js.snap
src/Emoji/index.ts
src/Icon/README.md

Added new component to properly render an emoji into a span with option to change size and add an a11y friendly label

Added Emoji Component

---

src/Button/Button.tsx

https://user-images.githubusercontent.com/25356097/104315407-cf236200-54d2-11eb-8081-68291f462379.mov
Disables the button when loading to prevent double click
Hides the icon as well when loading
- More buttons

Disable button when loading and hide icon when loading

---

src/Datepicker/Datepicker.stories.js
src/Datepicker/Datepicker.tsx

bug: 
fix:
Fixes a bug where calendar dates are not shifted correctly when the first day of the month is a Sunday
- Date picker

shift sunday correctly when first day of month

---

src/Icon/Icon.tsx
src/Icon/README.md

Adds the `person` icon to the Icon component
- Icon
- Icon/README.md

Add person icon

---

src/Datepicker/DatesList.tsx

Fixes an issue where the padding and grid gaps of the `DatesList` was breaking the UI on smaller screens. 
Grid-gaps and padding have now been adjusted for different media breakpoints.

Add additional breakpoint and scale padding/grid gaps

---

src/SearchInput/SearchInput.tsx

Allows displaying search results in a relative position.
This is because an absolute position doesn't quite work when inside a [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview).

🔎 Allow displaying search results in a relative position

---

.eslintrc
src/Button/Button.tsx
src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
src/theme.ts

- Changes for tertiary button styling
- Added `bg4` theme colour
- Removes types/eslint-prettier (as prettier now offers this in their main module)
- Updates snapshot testing

Tertiary button styling changes

---

CHANGELOG.md
src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
src/LabelledText/__tests__/__snapshots__/LabelledText.js.snap
src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap
src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap
src/Tag/Tag.tsx
src/Tag/__tests__/__snapshots__/Tag.js.snap
src/Text/README.md
src/Text/Text.tsx
src/Textarea/__tests__/__snapshots__/Textarea.js.snap

Add `label-large` to the Text Component.
Add `typo` to the Tag Component to style the inner test.

Add label-large for Text and add typo for Tag

---

.dependabot/config.yml

Adds Tracy to dependabot default reviewers and default assignees

Add Tracy to Smores dependabot config

---

CHANGELOG.md
src/Chip/Chip.tsx

- Adds border color for both states 
- Adds cursor pointer

GRW 432 - Chip styling changes

---

.github/workflows/import_icons.yml
.storybook/main.js

**This is a WIP test workflow**
As part of re-branding, the design team has organised a very nice page in Figma with all the new and refactored icons.
This workflow should export from that page all the icons in svg in the folder specified and it will be only triggered manually.
The reason behind is that when new icons come along we can create a new branch, trigger the workflow and then just import the new svgs in the existing `Icon` component that will then render.
**Next steps**
- when this is merged I'm gonna create a new branch to test the workflow and see if and how the import works
- if it's all good we can then think about all together how we want to clean up the old component and replace the hardcoded values with the new imported ones.
If you have any additional thoughts or …

added import icons workflow for initial test

---

CHANGELOG.md
src/Message/Message.stories.js
src/Message/Message.tsx

- Added linked properties for border and border color
- if `hasBorder` is true `borderColor` is required
- added string to `type` so we can use any icon we want

Added border and border color props for Message component

---

src/Message/Message.tsx
src/Message/__tests__/__snapshots__/Message.js.snap

Updates warning Message style to match new design.
Figma can be found [here](https://www.figma.com/file/FqSaizGOyOzXFZNmZ4X0LGMn/%F0%9F%8D%AC-S'mores?node-id=5361%3A7773)

Update warning Message style - ET-4458

---

src/TextInput/TextInput.stories.js
src/TextInput/TextInput.tsx

Currently it looks like this - added a margin to space them out

Add bottom margin to label if text input is outlined

---

src/Textarea/Textarea.tsx
src/Textarea/__tests__/__snapshots__/Textarea.js.snap

Changes the Textarea cursor to be text instead of pointer

Use text cursor instead of pointer for Textarea component

---

.github/CODEOWNERS
.prettierignore
CHANGELOG.md
src/Tag/Tag.tsx
src/Tag/__tests__/__snapshots__/Tag.js.snap

Fix styling to tag component / Mobile font was broken

Home-479 - Updated tag Component styles

---

CHANGELOG.md
src/Button/Button.stories.js
src/Button/Button.tsx
src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
src/Chip/Chip.stories.js
src/Chip/Chip.tsx
src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap

We can finally forward `ref` and any other default props (data and aria attributes for example) for `Button` and `Chip` components.
I've done these as a start since they are the most common use cases but if you think of any other that will need the same feel free to follow the same structure and improve them.

Forward Ref and default props for Button and Chip component

---

CHANGELOG.md
README.md
src/Accordion/Accordion.stories.js
src/Accordion/Accordion.tsx

Adding prop to Accordion to enable full border

Accordion with fullBorder prop

---

CHANGELOG.md
src/Dropdown/Dropdown.tsx

- No UI changes
- Make required property a passed-in prop on the Dropdown component
- Defaulting to true preserves any existing functionality relying on this prop 
- Will disable the default required validation message when using the Dropdown with react-hook-forms and yup validation

Fix - Make required prop in Dropdown component an optional prop on the component level

---

CHANGELOG.md
README.md
src/Dropdown/Dropdown.tsx
src/NumberInput/NumberInput.tsx
src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap
src/SearchInput/SearchInput.tsx
src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap
src/Text/Text.tsx
src/TextInput/TextInput.tsx
src/Textarea/Textarea.tsx
src/Textarea/__tests__/__snapshots__/Textarea.js.snap

- No UI changes
- Add missing props and forwardRef to `Text` component
- This addition allows to add the `htmlFor` attribute to labels on input components to use as selectors for tests

Add missing properties to Text component and link labels to input components

---

src/Button/Button.tsx
src/Button/LegacyButton.tsx

Update to make the `id` optional
See [slack thread](https://eatmarshmallows.slack.com/archives/CG7VD0QMA/p1643823081317959) for more context

Button - Make `id` prop optional

---

CHANGELOG.md
package-lock.json
package.json
src/Pagination/Pagination.tsx

- Fixes a bug with the pagination component where the last page is not updated if moving between a list that has more than 1 page and a list that has a single page.
- Fixes a bug with the pagination component where the "pages icons" are not updated if moving between a list that has more than 2 pages and a list that has two pages or less.

Ft pagination handle smaller page numbers

---

CHANGELOG.md
src/Button/Button.tsx

No error but some warning that isn't necessary

Update loading prop to be a transient prop

---

CHANGELOG.md
src/Button/Button.stories.js
src/Dropdown/Dropdown.tsx
src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap
src/SearchInput/SearchInput.tsx
src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap
src/TextInput/TextInput.tsx
src/TextInput/__tests__/__snapshots__/TextInput.js.snap
src/Textarea/Textarea.tsx
src/Textarea/__tests__/__snapshots__/Textarea.js.snap

https://user-images.githubusercontent.com/1053476/157431724-8f50ae2b-fcf4-441f-b1b4-3fce901740b9.mov
We lost hover state on form fields when we migrated to the new colour palette so I put it back in

Updated hover states for form fields and removed deprecated button stories

---

package-lock.json
package.json

⚠ WARNING: Starting from 31 March 2022, the protect command will be removed.
Please use the @snyk/protect package instead.
For more info: https://snyk.co/ueln7

Replace snyk with snyk/protect

---

src/Modal/Modal.stories.tsx
src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

| BEFORE | AFTER |
| ------------- | ------------- |
| ![Screenshot 2022-04-21 at 12 26 09](https://user-images.githubusercontent.com/14129033/164448366-47409a99-4dca-4cea-b6d7-9ed9f0c2a863.png) | ![Screenshot 2022-04-21 at 12 19 30](https://user-images.githubusercontent.com/14129033/164447888-0f66d77f-e48b-497f-9c47-d3b8937ed230.png)  |
- Add scrolling when the content is too long on desktop
- Updated scrolling property from `scroll` to `auto` on mobile, there should be no difference but this way, the scrolling bar isn't shown except when there is scrollable content

Add scrolling on desktop when content is too long

---

CHANGELOG.md
src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

Thought they were a z-index on the container, apparently not 🤡

add z-index to modal container

---

CHANGELOG.md
package-lock.json
package.json
src/ConfirmationRadioButtons/Confirmation.stories.tsx
src/ConfirmationRadioButtons/Confirmation.tsx
src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap

- Adds optional `label` prop for `Confirmation` component
- Updates `CHANGELOG` - adds missing version from previous version too
- Adds `With no label` definition in Storybook

Grw 1483 - Optional label prop for Confirmation

---

CHANGELOG.md
src/colors.stories.tsx
src/theme.ts

Added two new third parties colours

Added new third parties colours for home

---

CHANGELOG.md
src/Datepicker/Datepicker.tsx

**Allowing 31 days to be selected from 15th June**
before:
after:

stop always allowing today's date to be picked in datepicker

---

CHANGELOG.md
src/TextInput/TextInput.tsx

Add Lost trailingIcon to textInput

---

src/ConfirmationRadioButtons/Confirmation.tsx
src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap

- Radio buttons and label are now stacked rather than inline

Change Confirmation component label/radio buttons layout

---

CHANGELOG.md
src/Accordion/Accordion.tsx

- Border color was wrongly specified during the color migration
- Updated full border to match bottom border only

Fix outline color on accordion component 

---

README.md

Mentioning it in the call earlier made me realise we still have some mentions in places which are way outdated.
Travis CI must also not be relevant anymore.
And I'm not sure about that David thing, but it seems we're not getting data anymore?

Remove unused codacy badge

---

src/RadioGroup/RadioElement.tsx
src/RadioGroup/RadioGroup.stories.tsx
src/RadioGroup/RadioGroup.tsx
src/RadioGroup/RadioItem.tsx
src/utils/visuallyHidden.ts

Still in WIP but can be merged for now as it isn't exported, works that still needs to be done:
- Use `Fieldset` with some update around label
- Add error state
- Implement `displayType`: `vertical-card` and `horizontal-card`
Those will be done in the next few PRs

Setup `RadioGroup` structure

---

src/RadioGroup/RadioElement.tsx
src/RadioGroup/RadioGroup.stories.tsx
src/RadioGroup/RadioGroup.tsx
src/RadioGroup/RadioItem.tsx
src/RadioGroup/types.ts

Improved typing for the prop `value`, it should now infer what is the correct type and can be more precise than `string` when possible. The type of `value` is shared and used for both the prop `value` and `onChange`
- When the type is only `string`
- Using `boolean` as value
- Having a subset of `string`

Improve typing for `RadioGroup` value

---

src/Modal/Modal.tsx
src/Modal/__tests__/__snapshots__/Modal.js.snap

Here's the current behaviour, when the content doesn't have any hard constraints that would push the modal to it's max-width:
I believe, the default behaviour should be that the content is always at the max-width by default

fix Modal width

---

CHANGELOG.md
src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap
src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap
src/Textarea/__tests__/__snapshots__/Textarea.js.snap
src/fields/components/InternalField.tsx

There is some unneeded space at the top of the label because of the `Box`

Remove unwanted spacing above the label

---

CHANGELOG.md
src/SearchInput/SearchInput.tsx
src/utils/useControlledState.ts

- **Add `value` prop to `SearchInput`**
- **Implemented a `useControllableState`**: This logic can be re-used for our other form component at some point
When `stateProp` is `undefined`, we have an uncontrolled behaviour meaning that the state is handled inside the component
When `stateProp` is anything else, we have a controlled behaviour so the source of truth is now external and come from `value`

Add `value` prop to `SearchInput`

---

CHANGELOG.md
src/SearchInput/SearchInput.tsx
src/SearchInput/SearchOptions.tsx

The SearchInput has an issue that if multiple items in the list has the same value when you select one of them it will always display the first of the list as label.
e.g. for countries `Britain`, `UK` and `United Kingdom` all has the same option value as `GB`. If you search and select `UK` the searchInput will always display `Britain` because it's the first label that he finds with `GB` value.
This PR fixes that so if you search for `UK`, `UK` will be displayed in the input. It will still select `Britain` for any persisted value that we pass to `SearchInput` because we essentially lose the label associated to the value the we pass down as a prop and will fallback to the first one he finds in the search list. Not really sure if there's a real fix for it unless we find a way to pass down …

Fix searchInput when multiple items has the same value

---

.fossa.yml
.github/workflows/build_and_deploy.yml

[As requested here](https://eatmarshmallows.slack.com/archives/C8J3F9PN1/p1667389007431219?thread_ts=1667385398.687619&cid=C8J3F9PN1), this should run the fossa tool on every merge to main. We need to install the fossa CLI, and yq, then we use the FOSSA_API_KEY organization secret to run the analysis and upload it.

Add fossa analysis step to CI

---

CHANGELOG.md
src/Pagination/Pagination.tsx

https://user-images.githubusercontent.com/57456071/215477913-abd08fcb-bb84-4104-8681-6ba4f8f4b67b.mov
- Allows page number to be optionally passed from where the component is being used, allowing for active page to be maintained on hard refresh
- Previously we only store activePage in state & hard refresh always results in active page to be set to 1

Optionally set active page as prop for pagination

---

package-lock.json
package.json

Release version 2.16.0 to allow the use of the new `Tooltip` component

feat(version): bump to v2.16.0

---

CHANGELOG.md
src/Accordion/Accordion.tsx

Usage in action:
Figma design for CMS
Adding the ability to set the default open/close status for the `Accordion` component due to CMS needing this component to be open by default. This shouldn't affect any current usage of the `Accordion` component as the default is set to `false`

feat(accordion): defaultIsOpen prop for accordion status

---

.github/workflows/autoApproveDependabotPullRequests.yml

The [set-output command is deprecated for removal](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). This PR updates the auto approve workflow to use the GITHUB_OUTPUT env file instead.
This has been tested on the [uk-auto-quote-search](https://github.com/marshmallow-insurance/uk-auto-quote-search/blob/main/.github/workflows/autoApproveDependabotPullRequests.yml) repository.
<sub>PR generated using [multi-gitter](https://github.com/lindell/multi-gitter) from [this config file](https://github.com/marshmallow-insurance/Platform-multi-git-changes/blob/main/github-output-env-file/github-output-env-file.yaml)</sub>

Update auto approve workflow to use GITHUB_OUTPUT env file

---

CHANGELOG.md
src/Modal/useBodyScrollLock.ts

On mobile devices, body scroll lock works differently than on desktop and it was preventing to scroll inside the modal.
You could scroll using two fingers but it's very unintuitive, updated the options of the bodyScroll plugin to allow touchMove

Allow modal content to be scrolled on mobile devices when body is locked

---

CHANGELOG.md
package-lock.json
package.json
src/Icon/Icon.tsx

- updated 'minimise' and 'maximise' icons to allow colour to be changed by inserting: `fill={theme.colors[color]}`

fix(icons): allowing minimise and maximise icons to change colour

---

CHANGELOG.md
src/Snackbar/SnackbarContainer.tsx

Updating the `SnackbarContainer` to always be ontop with `z-index`

fix(snackbar): setting the z-index so it's always ontop

---

CHANGELOG.md
package-lock.json
package.json

Bumplestiltskin (I'm struggling for ideas on messages for bump PRs)

chore(version): bump from v2.18.3 to v2.18.4

---

CHANGELOG.md
src/Snackbar/SnackbarItem.tsx

Fix the snackbar `button` content to use a `span` for the text instead of the default `p`

fix(snackbar): use span tag for button content

---

CHANGELOG.md
src/TextInput/TextInput.stories.tsx
src/fields/commonFieldTypes.ts
src/fields/components/InternalField.tsx

Expand error message to be a react element. Needed for some Direct flow upgrades

Update error message to be React Element

---

src/IconStrict/IconStrict.stories.tsx
src/IconStrict/IconStrict.tsx
src/IconStrict/README.md
src/IconStrict/__tests__/IconStrict.js
src/IconStrict/__tests__/__snapshots__/IconStrict.js.snap
src/IconStrict/index.ts
src/colors.stories.tsx

**With background:**
Adds a new `IconStrict` component with strict sizes and an optional background colour. If a background colour is provided, the Icon is shrunk according to specified sizes.
Design document [here](https://www.notion.so/getmarshmallow/Iconography-f2b75f0162904dd89532a3af04871930)
FE RFC [here](https://www.notion.so/getmarshmallow/Iconography-ceb2bc82883b4f46a430e8ddd4b21da5)

Add new IconStrict component and story

---

src/Button/Button.stories.tsx
src/Button/Button.tsx
src/Button/Collection.tsx
src/Button/__tests__/Button.js
src/Button/__tests__/__snapshots__/Button.js.snap

Updates the Buttons component and stories in line with the rebrand
- Update Button colours
- Deprecate `tertiary` style and replace with `fallback`
- Add `textBtn` style with optional `trailingIcon`
FE RFC [here](https://www.notion.so/getmarshmallow/Buttons-0f02e12343c049f2938819262b690fe9)
Design [here](https://www.figma.com/file/FqSaizGOyOzXFZNmZ4X0LGMn/branch/QtMe0nsVPpPkgqtdqd2Op2/%F0%9F%8D%AC-S'mores?type=design&node-id=13006-107162&mode=design&t=f0OWcvekbOrxyb72-0)

Rebrand Buttons component

---

src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
src/Link/Link.stories.tsx
src/Link/Link.tsx

- Updates colours in line with rebrand
- Adds new `highlight` style
- Removes logic that renders new window icon if `openInNewTab` is `true`, and instead accept an optional `iconToRender` prop which accepts an icon string
- Default `iconToRender` to *new-window* if `openInNewTab` is `true` (this can be overridden by `iconToRender` string)
- Also add optional `isTrailingIcon` boolean property (true by default) and use this to render the icon after the link text if `true`, or before if `false`.
- Updates storybook
Figma [here](https://www.figma.com/file/FqSaizGOyOzXFZNmZ4X0LGMn/branch/QtMe0nsVPpPkgqtdqd2Op2/%F0%9F%8D%AC-S'mores?type=design&node-id=6862-26178&mode=design&t=vf4f4OrW36S5IfOL-0)
FE RFC [here](https://www.notion.so/getmarshmallow/Links-9605a5b45b154c96a9a78d495c0f2bca)

Rebrand Link component and update storybook

---

src/IconStrict/IconStrict.stories.tsx
src/IconStrict/IconStrict.tsx
src/IconStrict/__tests__/__snapshots__/IconStrict.js.snap
src/Modal/Modal.tsx

- Adds an optional `handleClick` to the `IconStrict` component
- Replaces the close icon with an `IconStrict` cross
- Updates the modal background colour and border radius
Figma [here](https://www.figma.com/file/FqSaizGOyOzXFZNmZ4X0LGMn/%F0%9F%8D%AC-S'mores?type=design&node-id=12298-86498&mode=design&t=np57oGZ05tr5netD-0)
FE RFC [here](https://www.notion.so/getmarshmallow/Modals-1b6fe38e50e743378861c1d037dc1e30)

Modals rebrand

---

src/CheckBox/CheckBox.tsx
src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap

- Increases border-radius of CheckBox
- Uses a `before` pseudo element as well as `after` to render the rounded tick

Update CheckBox border radius and tick

---

src/Link/Link.stories.tsx

- Updates the storybook prop to use `isTrailingIcon`

Update Link storybook trailing icon prop

---

CHANGELOG.md
src/Datepicker/Datepicker.tsx
src/Snackbar/SnackbarContainer.tsx

Changes to `Datepicker` and `SnackbarContainer` for CMS.
- Added ability to show the year on `Datepicker`
- Added ability to supply an end date to `Datepicker`
- Added ability to open the `Datepicker` on the current month or the selected value month
- Updated `SnackbarContainer` to always be ontop with z-index

chore: changes to datepicker and snackbar for CMS

---

.storybook/preview.tsx
src/Accordion/Accordion.tsx
src/Accordion/__tests__/__snapshots__/Accordion.js.snap
src/Banner/Banner.stories.tsx
src/Banner/BannerItem.tsx
src/Banner/types.ts
src/BrandCard/BrandCard.stories.tsx
src/Card/Card.stories.tsx
src/Loader/Loader.stories.tsx
src/Modal/Modal.tsx
src/Tag/Collection.tsx
src/Tag/Tag.stories.tsx
src/Text/fontMapping.ts
src/fontStyle.ts

- Adds new `MarshmallowYouth` font as the hero-alternate (replacing `ClearfaceITC`)
- Adds do `noTimeout` option to `Banner` component
- Updates `Accordion` border colour
- Updates `Tag` default colour
- Other small updates requested by design

Rebrand Typography and update tag

---

CHANGELOG.md
src/Divider/Divider.tsx
src/Text/fontMapping.ts

- Updates the `heading-alternate` font family to `MarshmallowYouth`
- Updates the default `Divider` colour to `oatmeal`

fix (rebrand): Small rebrand fixes 3

---

CHANGELOG.md
src/Accordion/Accordion.tsx
src/Datepicker/DatesList.tsx

The button type was 'submit' by default and was causing the page submit on direct signup.

Fix(rebrand): Fixes button type from default submit on datepicker

---

CHANGELOG.md
package-lock.json
package.json
src/ActionDropdown/ActionDropdown.tsx
src/ActionDropdown/__tests__/__snapshots__/ActionDropdown.js.snap
src/Table/Table.stories.tsx
src/Table/Table.tsx
src/Table/components/RowActions.tsx
src/Table/components/TableHeader.tsx
src/Table/components/TableRow.tsx
src/Table/components/commonComponents.tsx
src/Table/storyUtils.tsx
src/Table/types.ts

- adds headerHeight, maxWidth, noDataContent, truncateContent, noWrapContent props to Table

feat: adding more props to Table component

---

CHANGELOG.md
package-lock.json
package.json
src/Table/Table.stories.tsx
src/Table/Table.tsx
src/Table/components/RowActions.tsx
src/Table/components/TableHeader.tsx
src/Table/components/TableRow.tsx
src/Table/components/commonComponents.tsx
src/Table/types.ts

Before:
After:
- adds option to add `overflow: hidden` prop easily in the columns object, allowing for tooltips to show correctly.

fix: adding hideOverflow, rowActions bgColor, columnPadding, props to the Table

---

CHANGELOG.md
src/IconStrict/IconStrict.tsx
src/Table/Table.stories.tsx
src/Table/Table.tsx
src/Table/components/RowActions.tsx
src/Table/components/TableRow.tsx
src/Table/components/commonComponents.tsx
src/Table/storyUtils.tsx
src/Table/types.ts

https://github.com/marshmallow-insurance/smores-react/assets/57456071/9f9a6681-622c-4edc-b9d9-7b65488943b3
- adds clickableRow prop to Table, useful for quick navigation, adds `e.stopPropagation` to rowAction events to to prevent both onClicks firing, this cant be done for cells
- Caveat: ensure clickable cells have a the property e.stopPropagation on their onClick event

feat: add clickableRow prop to Table

---

CHANGELOG.md
src/Tooltip/Tooltip.stories.tsx
src/Tooltip/Tooltip.tsx

- fixes clipping issues if parent has overflow hidden
- - (removes position: relative on the parent)
- fixes alignment issue on underline if parent had height set

fix: tooltip overflow clipping

---

CHANGELOG.md
package-lock.json
package.json
src/Table/storyUtils.tsx
src/Tooltip/Tooltip.tsx

N/A
- accidentally renamed this for no reason

fix: rename tooltip position prop

---

CHANGELOG.md
package-lock.json
package.json
src/Button/Button.tsx

Issue - when `smallButton` and `textBtn` are combined, the padding remains.
Fixed - no padding when `smallButton` with `textBtn`
The `textBtn` prop does not have any padding, however when combined with `smallButton`, the padding property was overrriden.

Fix small textbtn padding

---

.github/workflows/bump_and_publish.yml

N/A
- adjusts the GH_TOKEN secret to be the `MARSHMALLOW_CI_PAT` which means @marshmallow-ci will author commits by the `semantic-releases-bot` - allowing us to bypass the branch protection

chore: adjust workflow to use marshmallow-ci PAT

---

.github/workflows/bump_and_publish.yml

N/A
- adds permissions as guided to here: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md

fix: adjusting Bump_and_Publish workflow

---

.github/workflows/bump_and_publish.yml

Updating the `bump_and_publish.yml` to pass the GitHub secret tokens to the `env` variables to be used when running the action.

fix(actions): add git author details to env variables

---

.github/workflows/bump_and_publish.yml

use GITHUB_TOKEN for the workflow github token.

fix(workflow): github token for bump and publish

---

.github/workflows/bump_and_publish.yml

Revert to using `MARSHMALLOW_CI_PAT`

fix(workflow): rever to MARSHMALLOW_CI_PAT

---

README.md
src/Toggle/Toggle.tsx
src/Toggle/__tests__/__snapshots__/Toggle.js.snap
src/tokenTest.spec.ts

- changes active state of `Toggle` to green
- updates README to include info about token expiries

style: convert Toggle active state to pistachio

---

.releaserc
package-lock.json
package.json

N/A
- adds the plugin for github releases to be automated when we run the `Bump & Publish` workflow

fix: add semantic-release GH-release plugin

---

src/LabelledText/LabelledText.tsx
src/SupportMessage/SupportMessage.stories.tsx
src/SupportMessage/SupportMessage.tsx
src/Table/components/RowActions.tsx
src/Table/components/TableRow.tsx
src/Table/helpers.ts
src/Tooltip/Tooltip.tsx
src/utils/isReactElement.ts

N/A
- fixes `validateDOMNesting(...): <div> cannot appear as a descendant of <p>` that would appear when using a ReactElement with SupportMessage description prop by adding in a ReactElement check
- fixes same error in Tooltip but instead by converting the UnderlinedText, <p /> component, to instead be a UnderlinedChild, <div /> component!
- adds labelBottom to LabelledText prop - to remove need for MarginlessLabelledText snowflake components

fix: validateDomNesting warnings in SupportMessage & Tooltip

---

src/Dropdown/Collection.tsx
src/Dropdown/Dropdown.tsx

- Adds an optional prop, `showDefaultOption` , to the `Dropdown` component to render a default selected option of "Select an option"
- Adds another optional prop, `customDefaultOption` that allows the user to override the "Select an option" value 
- Adds placeholder and show default option values to the dropdown `Collection.tsx`
- [Github Ticket](https://github.com/marshmallow-insurance/growth/issues/638)
- [Slack thread from Design](https://eatmarshmallows.slack.com/archives/C02U91D49C6/p1705658871408059)

feat(dropdown): allow placeholder to be used as empty value

---

src/Icon/Container.tsx
src/Icon/Icon.tsx

I've added some icons that we use in CMS, in preparation for the S'mores update. 
To do in CMS:
- rename icon `maximiseWindow` to `maximise-window`, to match naming pattern

feat: add icons used in CMS

---

src/NumberInput/Container.tsx
src/NumberInput/NumberInput.tsx
src/NumberInput/__tests__/NumberInput.js

- Fixes how numbers are rounded for currencies, previously if you tried to enter 100.01, when typing 100.0 javascript would stringify this to 100
- `strict` doesn't seem to be used anywhere so I've removed it, though keeping normalising with min & max

fix: fix NumberInput for currencies

---

.github/workflows/build_and_deploy.yml

- We're having some issues with the FOSSA api key and the build steps are set up this way in TeamCity
https://eatmarshmallows.slack.com/archives/C04CQU4U84T/p1707413197220079

Move FOSSA action to after deploy

---

src/CurrencyInput/CurrencyInput.tsx

https://github.com/marshmallow-insurance/smores-react/assets/5758372/cb394a5e-14f8-46a1-8149-e723987bc7c9
Update the currency component to allow for non decimal values. By default the component is set to decimal and requires the user to set `decimalNumber={false}` as a prop.

fix(currencyInput): allow non decimal inputs

---

src/Tooltip/Tooltip.stories.tsx
src/Tooltip/Tooltip.tsx

- allows us to pass zIndex to tooltip, altho the modal is set to 999 already - we can go over this
- passed portalContainer prop to tooltip too

fix: add zIndex & portalContainer props to tooltip

---

src/Dropdown/Dropdown.tsx

https://www.loom.com/share/cd346d9f47e744f7ac535e32a947114c
- The default option shown in the options list, should be disabled.
Following on [Slack](https://eatmarshmallows.slack.com/archives/C04QG0DUJJD/p1708082328198189?thread_ts=1708081655.209539&cid=C04QG0DUJJD)

Feat: makes placeholder option disabled

---

vite.config.ts

N/A
- the rollup caused this non-breaking error, but would cause some tests to fail: `TypeError: styled.div is not a function`
- can be seen happening to others here: https://arc.net/l/quote/ohybkqce
- the bug fix is here: https://arc.net/l/quote/uhzhtdqg

fix: typeErr from rollup of default import of styled-comp

---

package-lock.json

- Seems like we have a build error from deleting `package-lock.json`, This reverts the package-lock to the [previous working version](https://github.com/marshmallow-insurance/smores-react/pull/3531), with changes for bumped/added libraries in `package.json`

revert package-lock to fix build error

---

tsconfig.json

- skip type checking of node modules
- Looks like facebook use less strict settings for their typescript compiler, ours fails on `@lexical/react` when run locally
- [issue discussion](https://github.com/facebook/lexical/issues/2528)

skip lib check

---

src/RichTextEditor/RichTextEditor.tsx
src/RichTextEditor/storybook/Collection.tsx
src/RichTextEditor/storybook/RichText.stories.tsx

- bump version and release change to package.json
- add outline prop to rich text editor

fix: release @lexica/react package.json change and RichTextEditor outline prop

---

src/Pagination/Pagination.tsx
src/Pagination/__tests__/__snapshots__/Pagination.spec.tsx.snap
src/Pagination/storybook/Pagination.stories.tsx

- handle 3 digits on pagination component

fix: handle 3 digits on pagination component

---

src/Table/Table.tsx
src/Table/components/TableHeader.tsx
src/Table/components/commonComponents.tsx
src/Table/storybook/Table.stories.tsx
src/Table/types.ts

https://github.com/marshmallow-insurance/smores-react/assets/44034297/6df3b27c-9063-4a8c-affc-2db886dd5c96
On the credit hire page a requirement come from Alistair to have key line on the table 
[Design](https://www.figma.com/file/Gq8kllU6kzQ95pxfpf4sCX/Credit-Hire-add-on?type=design&node-id=1582-28408&mode=design&t=6unFNuGLxL3swsjp-0)
[Ticket](https://www.notion.so/getmarshmallow/Budapest-Kanban-Board-696ab44f2fa74d18846e44e27af1331c?p=44b0099ffb9242ddad318c3cc5910fa4&pm=s)
[Sub-Task](https://www.notion.so/getmarshmallow/Budapest-Kanban-Board-696ab44f2fa74d18846e44e27af1331c?p=132ffb6c22fb4a8fb2d741e9140d291c&pm=s)

Key line option to table

---

.husky/pre-commit
package-lock.json
package.json

N/A
This PR:
- upgrades [husky to v9](https://github.com/typicode/husky/releases/tag/v9.0.1)
- introduces the optional migration steps
```
v9 is backward compatible with v8, allowing you to freely upgrade and migrate your hooks later.
Here are the steps to migrate:
package.json
{
"scripts": {
-   "prepare": "husky install"
+   "prepare": "husky"
}
}
.husky/pre-commit
- #!/usr/bin/env sh
- . "$(dirname -- "$0")/_/husky.sh"
npm test 
Note: sh will be used to run hooks, even if a shebang is set.
If you were using husky as a module:
- const husky = require('husky')
- // ...
+ import husky from 'husky'
+ console.log(husky())
```
closes: https://github.com/marshmallow-insurance/smores-react/pull/3495
(stole from mats PR - https://github.com/marshmallow-insurance/uk-auto-signup-www/pull/6201)

bump: husky to v9

---

.storybook/main.ts
package-lock.json
package.json
tsconfig.build.json
tsconfig.json
vite.config.ts

- this shows storybook running locally
- also shows the comparison of the storybook build files and ensures static assets are created the same
https://github.com/marshmallow-insurance/smores-react/assets/57456071/5b9099d3-fb47-4f62-b067-af546db0d72b
- migration guide: https://arc.net/l/quote/qqxciuak
- ran: `npx storybook@latest upgrade` which did most of this
- v8 removed the auto creation of vite.config so we had to create our own ([link here](https://arc.net/l/quote/oebpypbu))
- v8 said to also remove storyStoreV7 to migrate ([link here](https://arc.net/l/quote/ovwusovm))
- v8 removed the -s command for serving static assets in the build, this is fixed by the main file changes (With the release of Storybook 8, the -s CLI flag was removed. We recommend using the [static …

bump: storybook v8

---

src/MarshformGenerator/MarshformGenerator.tsx

Updates the scaling on `MarshformGenerator` to be slightly bigger.

fix(marshform-generator): Updating scaling

---

src/RichTextEditor/RichTextEditor.tsx
src/RichTextEditor/storybook/Collection.tsx
src/RichTextEditor/storybook/Example.tsx
src/RichTextEditor/storybook/RichText.stories.tsx

- Change `defaultValue` to `value` in rich text editor (breaking change)
- Allow the value provided to the rich text editor to be updated - for use in email templating

breaking change: allow update default value for rich text editor

---

src/SupportMessage/SupportMessage.tsx

before
after
- updates support message success variant icon to the correct icon

fix: success supportMessage icon

---

package.json
src/Tooltip/Tooltip.tsx

N/A
- added this in and didnt realise we were importing this from another dependency and not explicitly declaring as a dependency
- removes use of `uuid` and replaces with `crypto.randomUUID()`

fix: remove uuid from tooltip

---

package-lock.json
package.json

N/A
Reverts marshmallow-insurance/smores-react#3709
- causing actions to fail: https://github.com/marshmallow-insurance/smores-react/actions/runs/8986485386/job/24682705192
- seems to be causing this issue: https://github.com/conventional-changelog/conventional-changelog/issues/1267

revert: conventional-changelog-conventionalcommits v8

---

.husky/commit-msg
commitlint.config.ts
package-lock.json
package.json
tsconfig.json

- husky check to check commit messages
- must use of of the conventional commit types
- is case sensitives
- can add more rules to this, but this a good base
- annoyingly i cant find a way for this to run before our `pre-commit-lint` that husky runs 
- setup guide: https://arc.net/l/quote/wulfvmzx
- commitlint repo: https://github.com/conventional-changelog/commitlint?tab=readme-ov-file#config

chore: add pre-commit conventional-commit husky check

---

src/Icon/iconFiles/Caret.tsx

N/A
Pass `className` to caret component to propagate styled component styles correctly

fix(caret): pass className to component

---

src/hooks/useBodyScrollLock/index.ts

[Demo](https://www.loom.com/share/67901f6475d84e03b82db99d8f86ba75)
Solves an issue for iOS devices where opening the modal would scroll body to the top of the screen.
- the change offsets the body by the scroll height when the modal is open
Solution based on https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/

fix: useBodyScrollLock

---

release.config.js
src/Datepicker/Datepicker.tsx
src/IconStrict/IconStrict.tsx
src/Table/types.ts

- Add `testid`s to datepicker buttons to allow for better testing
- Adds id to rowActions type for genericButton & iconButton
- Adjusts semantic-release config to patch version for chore releases

chore: add testid attributes to datepicker month buttons

---

package-lock.json
package.json

- bump ESLint to v8.57.0
Not bumped to v9 since we're waiting for typescript ESLint to fully release v8 that supports ESLint v9:
https://github.com/typescript-eslint/typescript-eslint/issues/8211#issuecomment-2106427365
- [Node.js 10, 13, and 15 are no longer supported](https://eslint.org/docs/latest/use/migrate-to-8.0.0#drop-old-node)
- [Removed codeframe and table formatters](https://eslint.org/docs/latest/use/migrate-to-8.0.0#removed-formatters)
- [comma-dangle rule schema is stricter](https://eslint.org/docs/latest/use/migrate-to-8.0.0#comma-dangle)
- [Unused disable directives are now fixable](https://eslint.org/docs/latest/use/migrate-to-8.0.0#directives)
- [eslint:recommended has been updated](https://eslint.org/docs/latest/use/migrate-to-8.0.0#eslint-recommended)
**tl;dr\***: …

chore: bump ESLint to v8.57.0

---

src/Table/Table.tsx
src/Table/types.ts

- Cleanup JSDoc of `Table` component to ensure we don't get a noisy blob when viewing the Storybook docs for the component

chore: cleanup noisy `Table` documentation

---

src/IconStrict/IconStrict.tsx

- Add `title` prop to allow adding the title attribute to `IconStrict`
- AP has a few icon buttons that have no tooltips to describe actions in text. Allowing adding the `title` attribute forces the browser to surface text when hovering these buttons

feat: Add 'title' attribute to  props

---

.github/dependabot.yml

- group more packages to avoid PR spam from dependabot
- explicitly only group `minor` and `patch` versions

chore: group related packages for dependabot

---

.github/dependabot.yml

Missed by https://github.com/marshmallow-insurance/smores-react/pull/3769
- get dependabot to group `storybook` with other storybook deps

chore: group `storybook` with other related deps

---

src/Table/Table.tsx
src/Table/storybook/Table.stories.tsx
src/Table/types.ts

Hidden table header in a subtable:
- Allows configuring tables to not render a table header. This is to support designs like this ([figma link](https://www.figma.com/design/SB6QnXvPF55xSNs3ohsK5W/Customer-Profile?m=auto&node-id=5168%3A50353&t=7Ngvn6Tc0RXtcxsY-1)):

feat: Add `hideTableHeader` prop to `Table`

---

package-lock.json
package.json

copied https://github.com/marshmallow-insurance/smores-react/pull/3792: bumping semantic-release from 23.1.1 to 24.0.0
`conventional-changelog-conventionalcommits` required to be bump with the `semantic-release` upgrade to 24.0.0
- Bump `semantic-release` from 23.1.1 to 24.0.0
- Bump `conventional-changelog-conventionalcommits` to 8.0.0

chore: bump `semantic-release` to 24.0.0 and `conventional-changelog-conventionalcommits` to 8.0.0

---

src/Badge/Badge.tsx

- Some badge props don't need to be required as we fallback to default values. Only `src` is required

fix(Badge): Change some badge props to be optional

---

src/Badge/index.ts
src/BadgeList/BadgeList.tsx
src/BadgeList/index.ts
src/index.ts

- We forgot to export the new `Badge` and `BadgeList` components
- Also export the types and enums for the components

fix: Export `Badge` and `BadgeList`

---

src/Table/components/RowActions.tsx
src/Table/storybook/storyUtils.tsx
src/Table/types.ts
src/Tooltip/Tooltip.tsx

(Part of hackathon)
Adding an optional tooltip to table row action buttons.
Will be used in agent portal to add a tooltip to invoice actions as shown on the screenshot.

feat(icon): add tooltips to table row action icon buttons

---

.github/dependabot.yml

- Group `lexical` libraries together when dependabot creates a PR to bump versions
Previous config had a typo and might've not been catching the extra segment e.g. `/`

chore(dependabot): group `lexical` libraries

---

src/Badge/Badge.tsx
src/Badge/BadgeFallbackImage.tsx
src/BadgeList/BadgeList.stories.tsx
src/BadgeList/BadgeList.tsx

- Fallback to using `title` when badge image fails to load. Uses first 2 characters of title

feat(Badge): Fallback to `title` when badge image fails to load

---

src/BadgeList/BadgeList.tsx

- Fix `limit` hiding a badge when we've only exceeded limit by 1

fix(BadgeList): Fix `limit` hiding a badge when we exceeded by 1

---

src/Badge/Badge.stories.tsx

N/A
- adds default title to badge storybook args
- stops accessibility tests from failing in CI

chore: add alt text to badge story to prevent accessibility test failing

---

src/Table/types.ts

Currently unable to add the `title` prop to a row action in a table, this change fixes this. Row action Icons ar currently defaulting to the `icon-button`.
- Allow adding `title` to row action

feat(Table-RowAction): Allow passing `title` to a row action

---

.github/dependabot.yml

We are getting dependabot PRs that is only updating the lockfile and not the package json aswell. We ideally want both to be in sync (even if they might not be required to be).
- Ensure dependabot keeps package json and lockfile versioning in sync
Dependabot PRs that are only changing lockfile:
- https://github.com/marshmallow-insurance/smores-react/pull/3854
- https://github.com/marshmallow-insurance/smores-react/pull/3853
- https://github.com/marshmallow-insurance/smores-react/pull/3852
Dependabot docs:
- [versioning strategy](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy)

chore(dependabot): Set versioning strategy to `increase`, ensuring package.json and lockfile are always in sync

---

src/Datepicker/Datepicker.tsx

No visual change 
Make availableMonths optional to het rid of the sentry warning 
https://marshmallow-insurance.sentry.io/issues/5285077374/?project=4504292403838976&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=3

fix(datepicker): optional availableMonths value

---

package-lock.json
package.json

Remove `@storybook/storybook-deployer`. This is no longer required since we've moved to github actions. This also removes the `deploy-storybook` script as it was linked to the package and not required.
This also resolves some NPM audit vulnerabilities
N/A
N/A
N/A

fix(npm): remove storybook deployer

---

src/CheckBoxGroup/CheckBoxGroup.tsx

add ability to CheckBoxGroup to align horizontaly 
[need for PA page cms ](https://www.notion.so/getmarshmallow/Budapest-Kanban-Board-696ab44f2fa74d18846e44e27af1331c?p=127eb18a3c33429e937bedb69f5ca1ca&pm=s)

feat(checkBoxGroup): add isColumn optional property

---

src/TextInput/TextInput.tsx
src/TextInput/storybook/Container.tsx
src/fields/components/CommonInput.tsx

- adds onAutoFill prop to the TextInput component
- checks for onAutoFillStart animation and to identify when autofill occurs
- this is needed as we use onBlur events for the majority of our fields, however, this does not trigger when a user uses autofill as the browser does not focus the input
NOTE:
- there is one issue with this solution demonstrated in the video though sometimes we can emit an event if a user has a partially entered value, and hovers over a choice for 2s (time taken for the animation duration to end) - not sure this is a huge issue since we will fire again once the user selects the option anyways
https://github.com/user-attachments/assets/bf3591dd-74e2-40ed-83c4-e6a32edda431

feat: add onAutoFill prop to TextInput

---

src/Datepicker/DatesList.tsx
src/RichTextEditor/plugins/ToolbarPlugin.tsx

We had a sentry issue about opening a window with an invalid URL. Added a try catch and a warn log to solve this.
Ticket: https://www.notion.so/getmarshmallow/SMORES-handle-invalid-url-error-41dd986c689e410fad731ad945d8067c
Sentry: https://marshmallow-insurance.sentry.io/issues/5796668815/?environment=production&project=4504292403838976&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=2

fix(RichTextEditor): invalid URL on new window open

---

src/Datepicker/DatesList.tsx

We had a [sentry issue](https://marshmallow-insurance.sentry.io/issues/5842385619/?environment=production&project=4504292403838976&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&sort=inbox&statsPeriod=14d&stream_index=0) coming from date picker with an undefined date, this PR aims to fix that.

fix(datePicker): first day error and undefined day

---

src/Table/components/RowActions.tsx
src/Table/types.ts

Refactor `RowAction` typing.
When `element` is present then `genericButton` and `iconButton` should not be passed.
This refactor ensures the type system understands this restriction and errors when fields are being passed that shouldn't.
For example, before you could do:
```tsx
{
element: <CustomButton />
iconButton: {
render: 'new-window',
backgroundColor: 'oatmeal',
size: 36,
tooltipText: 'Start in new tab',
},
onClick: (item) => handleStartReviewClick(item.policyNumber, item.reviewId, true),
},
```
Now the same will error
```tsx
{
element: <CustomButton />
iconButton: { // !! iconButton is not expected !!
render: 'new-window',
backgroundColor: 'oatmeal',
size: 36,
tooltipText: 'Start in new tab',
},
onClick: (item) => handleStartReviewClick(item.policyNumber, item.reviewId, true),
}, …
```

feat(rowActions): refactor `RowActions` typing to discriminated union type

---

src/Table/components/RowActions.tsx

No visual changes. Just adding more functionality
https://github.com/marshmallow-insurance/smores-react/actions/runs/11233376670
The way we've designed how we pass the `onClick` event to a table action is a little restrictive.
Because of this restriction, In AP, we want to run an action after `onClick` has finished, these changes allow us to await the `onClick` handler that is passed down to the custom `element` of a row action.
This **_SHOULD NOT_** change anything downstream as these `onClick` events are typed with a `void` return type - downstream services using this component **_SHOULD NOT_** be assigning the return value of the `onClick` function passed to a custom `element`.

feat(RowActions): Allow `onClick` events to be awaited

---

src/Link/Link.tsx

Fixes the default margin for the icon in the `Link` component to be 8px instead of 4px
- [Notion ticket](https://www.notion.so/getmarshmallow/Link-c895e77c1d1e49bf84e5630b91249aff?pvs=4)
- Visual

fix(link): default margin for icon

---

src/LabelledText/LabelledText.tsx

Updates the default `labelMargin` value in the `LabelledText` component from 8px to 4px.
- [Notion ticket](https://www.notion.so/getmarshmallow/Labelled-Text-3dcefac9e5a349a2a467ba06a735f1b3?pvs=4)
- Visual

fix(labelText): default to 4px

---

src/Chip/Chip.tsx

Fixes the icon size and min/max width for the Chip component
- [Notion ticket](https://www.notion.so/getmarshmallow/Chip-a3d2a61ef2d2414189f6e8ed16d3edcd?pvs=4)
- [Figma design](https://www.figma.com/design/FqSaizGOyOzXFZNmZ4X0LGMn/%F0%9F%8D%AC-S'mores?m=auto&node-id=14411-158465)
- Visual

fix(chip): icon size and min/max width

---

.github/workflows/bump_and_publish.yml
.github/workflows/preview_bump_and_publish.yml
README.md
package-lock.json
package.json
release.config.js

Allow for pre-releases on semantic branch prefixes including:
- `feature/*`
- `fix/*`
- `chore/*`
Removed prefix:
- `crumbs-*`
All accepted prefixes can create a pre-release that'll use the current lib version and suffix it with `crumbs-<branch-name>.x` (`x` being the next available pre-release version)
- As part of [FE discussion on Slack](https://eatmarshmallows.slack.com/archives/C06636QJ6Q4/p1728383695116449?thread_ts=1728382767.690179&cid=C06636QJ6Q4)
- Working on [CI](https://github.com/marshmallow-insurance/smores-react/actions/runs/11571164758/job/32208452065#step:5:107)

chore(release): Allow pre-release for semantic branch prefixes

---

src/Modal/Modal.tsx

- Allows `title` to be configurable, extending `Text` props
Retains previous functionality.
```tsx
<Modal title="MultiCar Account" />
```
```tsx
<Modal title={{ typo: 'hero', children: 'MultiCar Account' }} />
```
- Required for Modals with different title text sizes

feat(Modal): Make `title` configurable

---

src/Modal/Modal.tsx
src/SearchInput/SearchInput.tsx

- Add missing `title` to `IconStrict` usages. If we dont, it'll default to `'icon-button'`
**NOTE:** We should either:
- Make `title` a mandatory prop
- Or, stop defaulting title to `'icon-button'` and ignore any storybook tests that fail
> Problem

chore(IconStrict): Add missing `title` to `IconStrict` usages

---

src/SupportMessage/SupportMessage.tsx
src/SupportMessage/storybook/SupportMessage.stories.tsx

- Adds `rightSideComponent` prop, allowing right side of the `SupportMessage`'s content to be configurable
- Updated component story, using new [Component Story Format (CSF)](https://storybook.js.org/docs/api/csf) API
Needed to add text on the right side of the component (see below for images and a link to designs)
https://github.com/user-attachments/assets/b7c8f922-ad23-4466-8385-259a0f323392
> Storybook demo
- [Figma Designs](https://www.figma.com/design/SB6QnXvPF55xSNs3ohsK5W/Customer-Profile?m=auto&node-id=4942-89422&t=9mzKmwHzKdpJFDxM-1)
- closes https://github.com/marshmallow-insurance/multi-product/issues/662
- Used in https://github.com/marshmallow-insurance/uk-auto-agent-portal-www/pull/7339

feat(SupportMessage): Add `rightSideComponent` prop

---

vitest.config.ts

vitest config was not grabbing all appropriate test files - so running npm run test, would not actually test all file

chore: fix vitest config

---

src/NumberInput/NumberInput.tsx

- Prevent scrolling changing the number value
- No visual change
- Suggestion from FNOL testing: https://eatmarshmallows.slack.com/archives/C07P6AZ8VV0/p1733303228197279?thread_ts=1733239467.063109&cid=C07P6AZ8VV0

fix: prevent change on scroll for number input

---

.github/workflows/auto-merge-dependabot.yml
.github/workflows/autoApproveDependabotPullRequests.yml

This reverts commit b637866ab359a9dedabf9313d34f288425681ca4.
GitHub docs says we can't do this because smores is a public repo:
> [Actions and reusable workflows stored in private repositories cannot be used in public repositories](https://docs.github.com/en/actions/sharing-automations/sharing-actions-and-workflows-from-your-private-repository)

Revert "PE-1116 Use centralized dependabot auto-approve workflow (#4046)

---

src/utils/dateOfBirth/schema.test.ts
src/utils/dateOfBirth/schema.ts

Removes the createErrorMessage util that is [not used anywhere](https://eatmarshmallows.slack.com/archives/CG7VD0QMA/p1736183408876449). Both CMS and signup will be using the `dateOfBirthErrorMessages`.
n/a
n/a
Added units for the util

refactor: remove unused util

---

src/utils/dateOfBirth/dateOfBirthValidator.ts

[INT-68]
- Fix unable to build downstream apps because of missing import
When building out package assets, the asserts' imports aren't coerced into relative imports which break namespace imports like the one found in this PR.
Downstream
[INT-68]: https://marshmallow1.atlassian.net/browse/INT-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dateOfBirthValidator): Unable to build downstream apps because of missing import

---

package-lock.json
package.json
src/Badge/Badge.tsx
src/RadioGroup/RadioGroup.tsx
src/SearchInput/components/SearchOptions.tsx
src/SupportMessage/SupportMessage.tsx
src/Table/components/TableRow.tsx
src/Table/helpers.ts
src/Table/types.ts
src/fields/commonFieldTypes.ts
src/hooks/useClickOutside/index.ts
src/hooks/useEventListener/index.ts
src/utils/isReactElement.ts

[INT-69]
The [React 19 upgrade](https://github.com/marshmallow-insurance/smores-react/pull/4166) has caused types to error. PR here is to fix erroring types
These changes shouldn't be breaking as it should still work in the downstream apps that have older versions of React types (ones that don't have react 19 or 18.3 installed).
> [!NOTE] 
> These changes aren't breaking for downstream apps that haven't upgraded to React 19 yet as the inputs of the changed types haven't changed. Tested on `agent-portal-www` and found no issue.
Only typing changes
[INT-69]: https://marshmallow1.atlassian.net/browse/INT-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(React): Fix types after react 19 upgrade

---

package-lock.json
package.json

- adds playwright as specific devDep to ensure we are on the latest version (not axe-playwright specific) meaning GH actions should not break
- from this issue: https://github.com/microsoft/playwright/issues/33051

chore: adding playwright devDep to fix playwright install in CLI

---

release.config.js

- updates the `release.config.js` file to export the `config` object as a default export (esmodule format rather than commonjs, now that we have added the `type: module` in `package.json`

fix: semantic-release config as esmodule

---

src/RadioGroup/RadioGroup.tsx

PR to bump for a Major version for the following breaking changes:
1. Deleting `Emoji` and `Brandcard` components (unused internally)
2. Adjusting package.json to type: "module", this will require some changes for our components using Vitest
Steps to fix (2.)
Add the following to vitest.config - 
```
deps: {
inline: ['@mrshmllw/smores-react'],
},
```

bump: BREAKING CHANGES, type module and deleting components

---

src/Icon/iconsList.ts

PR to bump for a Major version for the following breaking changes:
1. Deleting `Emoji` and `Brandcard` components (unused internally)
2. Adjusting package.json to type: "module", this will require some changes for our components using Vitest
Steps to fix (2.)
Add the following to vitest.config - 
```
deps: {
inline: ['@mrshmllw/smores-react'],
},
```

BREAKING CHANGE: deleting BrandCard and Emoji components, adjusting package type to esm

---

.storybook/preview.tsx
src/fontStyle.ts

This PR removes any webflow url and replaces it with an assets.marshmallow.com url, webflow will be depreacted in the coming months. This PR was generated using multi-gitter

chore: Replace webflow url with marshmallow asset url

---

.github/workflows/autoApproveDependabotPullRequests.yml
.github/workflows/build_and_deploy.yml

This prevents supply chain attacks in case the action is exploited and overrides the tag with malicious code.

Pin third-party actions to specific commit shas

---

src/Toggle/Toggle.tsx

Added optional bgColor property for Toggle componnet

feat(toggle): added optional bgcolor for toggle component

---

src/Dropdown/Dropdown.tsx

adds relative positioning to the box wrapping the select component in the Dropdown component to ensure proper alignment of the front icon

fix: adding position relative to box wrapping select

---

src/Icon/Icon.tsx
src/ProgressIndicator/ProgressIndicator.test.tsx
src/ProgressIndicator/ProgressIndicator.tsx
src/ProgressIndicator/components/StepItem.test.tsx
src/ProgressIndicator/components/StepItem.tsx
src/ProgressIndicator/helpers.test.ts
src/ProgressIndicator/helpers.ts
src/ProgressIndicator/index.ts
src/ProgressIndicator/storybook/ProgressIndicator.stories.tsx
src/ProgressIndicator/types.ts

A new progress indicator component to show progress within form steps. This has the following props
- `steps`: An array of objects with the following properties
- `handleStepChange`: A function that runs on step change, does not run if the step is `disabled` (A step is considered `disabled` if it's not the current step or a completed step)
- `onStepClick`: A function that runs on step click. This is always run regardless of step state
- `simpleStep`: sets the component to a "simple" view (see below screenshots)
- `currentStep`: the current step the form should be on
> [!NOTE]
Whilst this is only used in the signup flow, this is part of the components library so we don't have any deviation going forward.
https://github.com/user-attachments/assets/2c4a31c1-41d1-4a3d-a135-b4e01fce555d …

feat(progress-indicator): new component

---

src/ProgressIndicator/ProgressIndicator.tsx
src/ProgressIndicator/components/StepItem.test.tsx
src/ProgressIndicator/components/StepItem.tsx

When implementing into SUF, I've needed to make the following changes
- Only allow the circle and text to be clickable
- Only show cursor pointer on clickable items
- Calculate step width only on visible steps
- Better styling changes to allow all clickable area
https://github.com/user-attachments/assets/d09057d3-aa1d-487b-9829-2a0ec517391f
https://github.com/user-attachments/assets/4da51b06-4597-44e6-b280-a3880d173828
N/A
- tests still pass

fix(progress-indicator): minor changes from implementation

---

src/ProgressIndicator/components/StepItem.tsx

Fixes an issue where the progress bar on smaller screens breaks the page and adds an overflow.
N/A
- Visual

chore(progress-indicator): better styling

---

src/ProgressIndicator/components/StepItem.tsx

- Minor UI adjustment to fix when the "full" indicator leaves a gap in some cases.
- Adding a test Id to the clickable area for better testing
N/A
N/A
Visual

chore: move step item full indicator and add test id to clickable area

---

src/Tag/Tag.tsx

Added optional onClick property for Tag componnet

feat(tag): added optional onclick prop to tag comp

---

src/Dropdown/Dropdown.tsx
src/RadioGroup/RadioItem.tsx

Changed the styling of the radiogroup if the option is disabled, changed font color of placeholder text
PR is part of this ticket: https://marshmallow1.atlassian.net/browse/CLM-1364

feat(radiogroup): radiogroup and dropdown style

---

src/Table/types.ts

Follow-up from https://github.com/marshmallow-insurance/smores-react/pull/4433
Accidentally left an unused `footerColor` property. Haven't release previous changes so safe to remove without breaking.
Eliminate the unused footerColor property from the TableProps interface to streamline the code.

chore(Table): remove redundant `footerColor` prop from TableProps interface

---

src/IconStrict/IconStrict.tsx

- Always use the title attribute when it is present, regardless of whether the icon is rendered as a button or another element.

refactor(IconStrict): Use `title` regardless of `isButton`

---

src/RadioGroup/RadioGroup.tsx
src/RadioGroup/storybook/RadioGroup.stories.tsx
src/RadioGroup/types.ts

Temporary Enhancement: Add horizontal-normal Display Type to RadioGroup
This pull request introduces a temporary display type, horizontal-normal, to the RadioGroup component. This addition addresses immediate design requirements without introducing breaking changes, ahead of a planned refactor of the component for improved flexibility and maintainability.
Key Updates:
•	New Display Type: Added horizontal-normal to the DisplayType type definition to meet specific layout needs. This implementation is explicitly intended as a short-term solution.
•	Styling Logic: Updated the RadioItemList component to support the new display type, using a switch statement to cleanly handle different layouts.
•	Storybook Documentation: Added a new story (HorizontalNormal) to demonstrate and test the new …

feat(RadioGroup): add 'horizontal-normal' display type and update styles

---

.github/dependabot.yml

This change migrates the deprecated dependabot `reviewers` and `assignees` to a `.github/CODEOWNERS` file:
- Extracts all team references from `reviewers` and `assignees` properties in `.github/dependabot.yml`
- Creates a new `.github/CODEOWNERS` file (if one doesn't already exist) with these teams as global code owners
- Removes the `reviewers` and `assignees` properties from the dependabot configuration
This approach centralizes code review assignments through CODEOWNERS while maintaining the same review process for dependabot PRs.
<small>PR generated using [multi-gitter](https://github.com/lindell/multi-gitter) from [this config file](https://github.com/marshmallow-insurance/Platform-multi-git-changes/blob/main/dependabot-codeowners/migrate-dependabot-to-codeowners.yml)</small>

Migrate dependabot reviewers/assignees to CODEOWNERS

---

src/Accordion/Accordion.test.tsx
src/Accordion/__snapshots__/Accordion.test.tsx.snap
src/Button/Button.test.tsx
src/Button/__snapshots__/Button.test.tsx.snap
src/Card/Card.test.tsx
src/Card/__snapshots__/Card.test.tsx.snap
src/CheckBox/CheckBox.test.tsx
src/CheckBox/__snapshots__/CheckBox.test.tsx.snap

Adds snapshot tests to the following components as part of gradual snapshot testing implementation to key components/variants:
- Accordion
- Button
- Card
- Checkbox
N/A
Prerequisite of the ongoing Design System tokenisation work
✅ Snapshot tests added to four components

feat(testing): add snapshot tests to 4 components

---

src/CheckBox/CheckBox.tsx
src/CheckBox/__snapshots__/CheckBox.test.tsx.snap

- Update checkbox to use theme provider
- fixes an issue where `border` turned black if the error boolean is true
https://github.com/user-attachments/assets/f63889ce-757c-42c5-a289-1fe100c94c26
N/A
- unit tests still pass
- snapshots updated

chore(checkbox): use theme provider [DES-50]

---

src/Snackbar/SnackbarItem.test.tsx
src/Snackbar/SnackbarItem.tsx
src/Snackbar/__snapshots__/SnackbarItem.test.tsx.snap

- Updates snackbar to use theme provider
https://github.com/user-attachments/assets/5521fe9d-9aca-4382-b4e8-72015efb04ae
N/A
- unit tests added
- snapshot tests added

chore(snackbar): update to use theme provider [DES-75]

---

src/ThemeProvider/utils/colourMap.ts

- Fixes the typing for the colour variables by updating the path import
N/A
N/A
- Using yalc

fix(theme): correct import to fix typing

---

src/Accordion/Accordion.tsx
src/Accordion/__snapshots__/Accordion.test.tsx.snap
src/Accordion/storybook/Accordion.stories.tsx
src/ThemeProvider/utils/colourMap.ts

- Updates the `Accordion` component to resolve the border & background colours to the theme colours provided.
- Adds and uses a `resolveToThemeColor` to help resolve colours easier
> [!NOTE]
> The Accordion component will be deprecated and replace/updated with a new variant soon so I have chosen to still use the old colour values but resolve to the correct theme color.    
https://github.com/user-attachments/assets/a495f195-f020-4345-9f12-2d7e43c77ccf
N/A
- Snapshot tests updated

feat(accordion): resolve border and background to theme colours [DES-42]
