marshmallow-insurance/smores-react

src/Toggle/Container.jsx, src/Toggle/Toggle.stories.js, src/Toggle/Toggle.tsx, src/Toggle/__tests__/Toggle.js, src/Toggle/__tests__/__snapshots__/Toggle.js.snap, src/Toggle/index.ts, src/index.ts
New component - `Toggle`.
[A specific checklist to show the progress of the PR]
=> add Toggle component

src/theme.ts
Add stripe colour to the theme
etc.)
=> Task / Add stripe colour to the theme

src/Dropdown/Dropdown.stories.js, src/Dropdown/Dropdown.tsx
It automatically selects the only option when the dropdown list only has one item.
- Any dropdowns in Agent Portal or Customer Account that only has 1 item
=> Auto-select single item Dropdown

src/Tag/Tag.stories.js, src/Tag/Tag.tsx, src/Tag/__tests__/Tag.js, src/Tag/__tests__/__snapshots__/Tag.js.snap, src/Tag/index.ts, src/index.ts
Add a simple `Tag` component to Smores.
- Add Tag component
- Add simple snapshot test for the component
etc.)
=> Add Tag component

src/Dropdown/Dropdown.stories.js, src/Dropdown/Dropdown.tsx, src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap, src/TextInput/TextInput.stories.js, src/TextInput/TextInput.tsx, src/TextInput/__tests__/__snapshots__/TextInput.js.snap
Add disabled state to the TextInput and update disabled state on Dropdown.
- Adds disabled state and styles for the TextInput component
- Updates disabled styles for the Dropdown component
- Updates tests
=> Add disabled state to the TextInput and update disabled state on Dropdown

src/Tag/Tag.stories.js, src/Tag/Tag.tsx, src/Tag/__tests__/__snapshots__/Tag.js.snap
Update the style of the Tag component.
- Update the style of the Tag component
- Update tests
=> Update the style of the Tag component

src/Textarea/Container.jsx, src/Textarea/Textarea.stories.js, src/Textarea/Textarea.tsx, src/Textarea/__tests__/Textarea.js, src/Textarea/__tests__/__snapshots__/Textarea.js.snap, src/Textarea/index.ts, src/index.ts
Add a `Textarea` component to the project.
- Add a `Textarea` component to the project
- Add stories for the default, error and disabled states
- Add tests for the component
- Need to bare in mind that when integrating into the Agent Portal we'll need to add in some missing positional styles
=> Add Textarea component

.prettierrc, src/CheckBox/CheckBox.tsx, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
Update spacing on between the input and the description as per the designs.
=> Update spacing on the Checkbox as per the designs

src/Dropdown/Container.jsx, src/Dropdown/Dropdown.stories.js, src/Dropdown/Dropdown.tsx
Fix the dropdown component to that it rerenders (resets) when it's list of options changes.
- Update `Dropdown.tsx`
- Update story and add container
=> Fix dropdown dynamic list

package-lock.json, src/Dropdown/Dropdown.tsx
Prevent the app from exploding if an empty **list** prop provided to a `<Dropdown />`
`<Dropdown />` component
=> Fix Dropdown empty list issue

src/LabelledText/LabelledText.stories.js, src/LabelledText/LabelledText.tsx, src/LabelledText/__tests__/LabelledText.js, src/LabelledText/__tests__/__snapshots__/LabelledText.js.snap, src/LabelledText/index.ts
Add `LabelledText` component as it is used in both the Agent Portal and the Customer Account.
- Add `LabelledText` component
=> Add LabelledText component

package.json, src/Icon/Icon.stories.js, src/Icon/Icon.tsx, src/Icon/README.md
Add info icon and update the package.json
=> Add info icon

package-lock.json, package.json, src/Datepicker/Datepicker.stories.js, src/Datepicker/Datepicker.tsx, src/Datepicker/DatesList.tsx, src/Datepicker/__tests__/Datepicker.js, src/Datepicker/__tests__/__snapshots__/Datepicker.js.snap, src/Datepicker/index.ts, src/Datepicker/types.ts, src/theme.ts
Move date picker component to from Customer Account to Smores library.
- Add `Datepicker` component to Smores
- Add types for Date and Month
- Update snapshot tests
=> Add date picker component to Smores

src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/Datepicker/__tests__/__snapshots__/Datepicker.js.snap, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/theme.ts
Add orange and dark orange to the theme.
- theme.ts
=> Add orange and dark orange to the theme

src/Message/Message.tsx, src/Message/__tests__/__snapshots__/Message.js.snap
Remove label wrapper from around children prop so that you can put a wider array of items inside the Message component.
=> Remove label wrapper from around children prop

.eslintrc, package-lock.json, package.json, src/Message/Message.stories.js, src/Message/Message.tsx, src/Message/__tests__/Message.js, src/Message/__tests__/__snapshots__/Message.js.snap
Update Message component so that the icon can be placed at the top, middle or bottom of the card.
- Message.tsx, stories and tests
=> Update Message component

src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap, src/Icon/Icon.stories.js, src/Icon/Icon.tsx, src/Icon/README.md, src/Icon/__tests__/Icon.js, src/Icon/__tests__/__snapshots__/Icon.js.snap, src/Message/__tests__/__snapshots__/Message.js.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap
• Added new "plus-circle" icon
• Extend the `Icon` component to accept the margin props: `mt, mr, mb, ml` (_: string_)
- `Icon.tsx` component
[A specific checklist to show the progress of the PR]
=> ➕add new icon, add margin props

.travis.yml, package-lock.json
Bump Node version so that jest doesn't break when being run in Travis.
=> Fix error with dependencies

src/Message/Message.stories.js, src/Message/Message.tsx, src/Message/__tests__/__snapshots__/Message.js.snap
- Add an "**Inverted**" prop to `<Message />` component.
=> 👾 add inverted prop to Message component

src/ActionDropdown/ActionDropdown.stories.js, src/ActionDropdown/ActionDropdown.tsx, src/ActionDropdown/List.tsx, src/ActionDropdown/__tests__/ActionDropdown.js, src/ActionDropdown/__tests__/__snapshots__/ActionDropdown.js.snap, src/ActionDropdown/index.ts, src/Message/__tests__/__snapshots__/Message.js.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/Tag/__tests__/__snapshots__/Tag.js.snap, src/Textarea/__tests__/__snapshots__/Textarea.js.snap, src/theme.ts
- Introduce a new `<ActionDropdown />` component aka a "Rich" Dropdown with custom UI.
- This component isn't optimized for mobile devices
=> 🎹 implement ActionDropdown

src/CheckBox/CheckBox.stories.js, src/CheckBox/CheckBox.tsx, src/CheckBox/Container.jsx, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
Update CheckBox to the new square style.
=> Update CheckBox to the new square style

src/theme.ts
Updates theme.ts to include `cyan5` and `premfina orange`
- theme.ts
=> Update theme.ts to include two new colours

.dependabot/config.yml
Remove Todor and add Ella to Dependabot config
=> Remove Todor and add Ella to Dependabot config

src/theme.ts
Adds colours for fraud checks as defined [here](https://www.figma.com/file/FqSaizGOyOzXFZNmZ4X0LGMn/%F0%9F%8D%AC-S'mores?node-id=2801%3A834).
- `theme.ts`
=> Add fraud check colours

src/Datepicker/Datepicker.tsx
Update the position of the left and right arrows on the datepicker so they are properly center-aligned.
=> Update position of the caret

.dependabot/config.yml
Add Habs to dependabot config.
=> Add Habs to dependabot config

README.md
Adds release instructions to README
- README.md
=> Update README to include release instructions

.dependabot/config.yml
Updates dependabot assignees and adds reviewers
- dependabot/config.yml
=> Updates dependabot reviewers and assignees

package.json, src/SearchInput/SearchInput.tsx, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap
Add optional name attribute to SearchInput
=> Add name attribute to SearchInput and bump @storybook/react

src/Message/Message.stories.js, src/Message/Message.tsx, src/Message/__tests__/__snapshots__/Message.js.snap
Remove inverted style and update the style of the Message component.
- A small update to the AP and CA will be incoming after this.
=> Remove inverted style and update Message component

package-lock.json, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/LabelledText/__tests__/__snapshots__/LabelledText.js.snap, src/Modal/__tests__/__snapshots__/Modal.js.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/Tag/__tests__/__snapshots__/Tag.js.snap, src/Text/Text.stories.js, src/Text/Text.tsx, src/Text/__tests__/__snapshots__/Text.js.snap, src/Textarea/__tests__/__snapshots__/Textarea.js.snap
Added title attribute to Text component
=> added title attribute to text component and updated outdated snapshots

src/Icon/Icon.tsx, src/Icon/README.md
=> Added clock icon

src/Modal/Modal.tsx, src/Modal/__tests__/__snapshots__/Modal.js.snap
Added an optional icon prop to modal
- Modal
=> added icon prop to modal

src/Modal/Modal.stories.js, src/Modal/Modal.tsx, src/Modal/__tests__/__snapshots__/Modal.js.snap
From:
To: 
Layout fixes to the modal icon
- Modal
=> fixed icon size and layout

src/Modal/Modal.stories.js, src/Modal/Modal.tsx, src/Modal/__tests__/__snapshots__/Modal.js.snap
Using flex for centring the modal horizontally and vertically, to ensure it is properly centred on pages longer than the viewport.   
- Modal
=> use flex to properly center modal on scrolling pages

src/Button/Button.tsx
- Passes icon color input as set string instead of hex
=> Changes colour input for icon

src/Datepicker/Datepicker.stories.js, src/Datepicker/Datepicker.tsx
Optional prop to set a date the date picker should start from
- Date picker
=> date picker optional date from prop

src/Modal/Modal.tsx, src/Modal/__tests__/__snapshots__/Modal.js.snap
- Modal now has position fixed
=> ensure modal is always fixed

src/theme.ts
Need a new shade of yellow for Fraud Queues
=> Added new shade of yellow to theme

.dependabot/config.yml
Remove myself from dependabot config
=> Remove myself from dependabot config

package-lock.json, package.json, src/Pagination/Pagination.stories.js, src/Pagination/Pagination.tsx, src/Pagination/__tests__/Pagination.js, src/Pagination/__tests__/__snapshots__/Pagination.js.snap, src/Pagination/index.ts
=> Add pagination

.github/pull_request_template.md, README.md
Updates the PR template to use new format.
Also updates README section on checking the build is successful.
- PR template
- README
=> Update pr template

src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/RadioButton/__tests__/__snapshots__/RadioButton.js.snap, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/TextInput/__tests__/__snapshots__/TextInput.js.snap, src/Textarea/__tests__/__snapshots__/Textarea.js.snap, src/Toggle/__tests__/__snapshots__/Toggle.js.snap, src/theme.ts
=> Updated grey4 value

.github/workflows/release.yml, .prettierignore, CHANGELOG.md, README.md
After this PR is merged, every tag push will trigger the new release workflow that will create a release and populate it from `CHANGELOG.md`
Once this is released we need to remember to populate `CHANGELOG.md` with what we are releasing either during release process or as part of the branch with the new feature or fix.
=> Added release workflow

.github/CODEOWNERS
=> Introducing code owners to the repo

CHANGELOG.md, package-lock.json, package.json
=> Roll back typescript version

.github/CODEOWNERS, src/Chip/Chip.stories.js, src/Chip/Chip.tsx
=> Chip loading and disabled states

CHANGELOG.md, src/Chip/Chip.tsx
Forgot to make loading and disabled optional 
=> Optional added for loading and disabled

package-lock.json, src/Modal/Modal.tsx
Adds a `containerClass` to the Modal container so that styles are extendable via `className`
=> Add modal classname

CHANGELOG.md, src/TextInput/TextInput.tsx
Added pattern prop to text inputs and updated changelog to release
=> Update text input

CHANGELOG.md, src/Button/Button.stories.js, src/Button/Button.tsx
Adding `form` attribute to buttons so we can use them to submit specific forms based on ID across a whole page
=> Added form attribute to Button component

package-lock.json, package.json
=> Release prep 2

CHANGELOG.md, src/LabelledText/LabelledText.tsx
=> Update labelled text

CHANGELOG.md
=> Changelog typo update

CHANGELOG.md, src/NumberInput/NumberInput.tsx, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/TextInput/TextInput.tsx, src/TextInput/__tests__/__snapshots__/TextInput.js.snap
Set height to auto in order to avoid cutting container for outlined fields
=> fixed height for form fields

CHANGELOG.md, jest.config.js, src/Dropdown/Dropdown.tsx, src/NumberInput/NumberInput.tsx, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/SearchInput/SearchInput.tsx, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/TextInput/TextInput.tsx, src/Textarea/Textarea.tsx, src/Textarea/__tests__/__snapshots__/Textarea.js.snap
Changed all label colour to grey8
=> Updated label colour for form fields

src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/Textarea/Textarea.tsx, src/Textarea/__tests__/__snapshots__/Textarea.js.snap
Adds `maxLength` prop to Textarea component
=> Add maxLength prop to Textarea

README.md
Updates readme to reflect new release process.
=> Update readme with new release instructions

src/TextInput/TextInput.stories.js, src/TextInput/TextInput.tsx
added two new handlers to TextInput onInputChange and onBlur
=> added on change input handler

CHANGELOG.md, src/Chip/Chip.stories.js, src/Chip/Chip.tsx
=> Fix loading state on chip component

CHANGELOG.md, src/TextInput/TextInput.tsx
added time and date as types to text input
=> added date and time to text input

src/Accordion/Accordion.stories.js
=> Accordion fullBorder story

package-lock.json, package.json
=> release prep 1.5.0

CHANGELOG.md, src/Dropdown/Dropdown.stories.js, src/Dropdown/Dropdown.tsx, src/Dropdown/__tests__/Dropdown.js, src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap
Introduces optional [<optgroup>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) labels to dropdown items.
=> Introduce optional <optgroup> label to DropdownItem

CHANGELOG.md, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap, src/Icon/Icon.tsx
=> fixed icon size

src/CheckBox/CheckBox.stories.js, src/CheckBox/CheckBox.tsx, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap
- Add optional error state (red outline) and optional error message (below checkbox)
=> Add error state and optional message to Checkbox

CHANGELOG.md, package-lock.json, package.json, src/ActionDropdown/ActionDropdown.stories.js, src/ActionDropdown/Container.jsx, src/ActionDropdown/__tests__/ActionDropdown.js, src/ActionDropdown/__tests__/__snapshots__/ActionDropdown.js.snap, src/Button/Button.tsx, src/CheckBox/CheckBox.tsx, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/Icon/README.md, src/Loader/Loader.stories.js, src/Loader/__tests__/Loader.js, src/Loader/__tests__/__snapshots__/Loader.js.snap, src/Message/Message.tsx, src/Message/__tests__/__snapshots__/Message.js.snap, src/Row/Row.stories.js, src/Text/README.md, src/Text/Text.stories.js
- Added polished library to handle darken colours for button hover
=> Minor hover updates with new colours

.github/CODEOWNERS, .github/dependabot.yml
=> Added Mickael to codeowners and dependabot

src/ActionDropdown/__tests__/__snapshots__/ActionDropdown.js.snap, src/theme.ts
Fix wrong color value, `warning` and `agentWarning` were swapped
=> fix color value

.eslintrc, src/colors.stories.js
Added a story for the colors with the name, the hex and the color displayed as well
=> Add color story

CHANGELOG.md, src/Button/Button.tsx
- fixed primary and tertiary buttons border colour on hover
=> Button border hover

CHANGELOG.md, src/Icon/Container.jsx, src/Icon/Icon.tsx
- Adds the `repeat-charge` Icon
=> Add repeat charge icon

.github/workflows/autoApproveDependabotPullRequests.yml
=> workflow to automerge dependabot prs

CHANGELOG.md, src/CheckBox/CheckBox.tsx, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/CheckBoxGroup/CheckBox.tsx, src/CheckBoxGroup/CheckBoxGroup.stories.js, src/CheckBoxGroup/CheckBoxGroup.tsx
=> Top align multiline labes in checkboxes

src/Pagination/Pagination.tsx
=> Use 0 instead of null

.storybook/main.js, .storybook/preview.js, package-lock.json, package.json
**Check link for more details:**
https://storybook.js.org/addons/storybook-addon-performance
There is no impact on the library but just an additional tool that can be used to get additional data around performance
=> Storybook - add performance add-on

CHANGELOG.md, package-lock.json, package.json, src/Button/Button.stories.js, src/Button/Button.tsx, src/Button/InteractivePlayground.tsx, src/Button/__tests__/__snapshots__/Button.js.snap
**BEFORE**
https://user-images.githubusercontent.com/14129033/156031389-6dd916a6-1b3f-4dfb-be19-829a7246de38.mov
The button has a height of 52px but when an icon is present, it goes to 60px ([link to the storybook](https://marshmallow-insurance.github.io/smores-react/?path=/story/button--icon)).
When going to a loading state, the button size changed as well
**AFTER**
https://user-images.githubusercontent.com/14129033/156031419-aaf92b55-482f-49d8-8d6f-5ccb32ff36a9.mov
The button stays at 52px height and there is no size change during loading state change
=> fix button layout shifting when a icon is present or when loading

package-lock.json, package.json
=> Bump version to v2.1.8

CHANGELOG.md, package-lock.json, package.json, src/Accordion/Accordion.tsx
https://user-images.githubusercontent.com/99182828/158162401-114e3f93-1bad-4772-bd8a-9add7ac774c1.mov
- Reduces and removes spacing for Accordion component (requested by Luke who has gotten the OK from rest of design)
=> Grw 1270 - Accordion component

.storybook/preview-head.html
We can improve it going forwards but at least it's a start
=> Reset margin and padding in storybook

src/Button/Button.stories.tsx, src/Button/Collection.tsx
=> Improve Button stories structure

CHANGELOG.md, package-lock.json, package.json
=> Bump version to v2.1.20

src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap, src/LabelledText/__tests__/__snapshots__/LabelledText.js.snap, src/Link/Link.stories.tsx, src/Link/Link.tsx, src/Link/index.ts, src/Modal/__tests__/__snapshots__/Modal.js.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/Pagination/__tests__/__snapshots__/Pagination.js.snap, src/Row/__tests__/__snapshots__/Row.js.snap, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/Tag/__tests__/Tag.js, src/Tag/__tests__/__snapshots__/Tag.js.snap, src/Text/Text.tsx, src/Text/__tests__/__snapshots__/Text.js.snap, src/Textarea/__tests__/__snapshots__/Textarea.js.snap
[Related RFC](https://www.notion.so/getmarshmallow/Link-RFC-934e63db272d414f98313c25c7f96321)
Waiting a few days just in case anyone has a comment but ready to be reviewed
=> add link component

CHANGELOG.md, src/ActionDropdown/ActionDropdown.tsx, src/ActionDropdown/Container.tsx, src/ActionDropdown/List.tsx, src/Button/Button.tsx, src/Button/LegacyButton.tsx, src/CheckBox/CheckBox.tsx, src/ConfirmationRadioButtons/Confirmation.tsx, src/Divider/Divider.tsx, src/Icon/Icon.tsx, src/Loader/Loader.tsx, src/Row/Row.tsx, src/Tag/Tag.tsx, src/Text/Text.tsx, src/colors.stories.tsx, src/theme.ts, tsconfig.json
=> Improve components typing and remove `suppressImplicitAnyIndexErrors`

opslevel.yml
Added more wiki docs in opslevel
=> updated opslevel toold adding more documentation

src/Dropdown/Dropdown.tsx, src/SearchInput/SearchInput.tsx, src/TextInput/TextInput.tsx, src/Textarea/Textarea.tsx
=> Add ref properly to input components

CHANGELOG.md, src/Datepicker/Datepicker.tsx, src/Datepicker/DatesList.tsx, src/Datepicker/types.ts
=> Fix Datepicker range display

CHANGELOG.md, src/Datepicker/Datepicker.tsx, src/utils/date.ts
=> Set time zone to UK

CHANGELOG.md, src/Text/Text.stories.tsx
=> Typography story

CHANGELOG.md, src/Tag/Tag.stories.tsx, src/Tag/Tag.tsx, src/Tag/__tests__/__snapshots__/Tag.js.snap
- Adds new boolean prop for styled gradient tag using `bgGradient`
- Adds to stories
=> BgGradient pink tag

CHANGELOG.md
- Missed comments on [previous PR](https://github.com/marshmallow-insurance/smores-react/pull/2037)
=> add missing changelog items

CHANGELOG.md, src/Dropdown/Dropdown.tsx, src/Field/index.ts, src/SearchInput/SearchInput.tsx, src/TextInput/TextInput.tsx
=> Fixed CommonFieldTypes imports

.lintstagedrc, src/TextInput/TextInput.tsx, src/TextInput/__tests__/__snapshots__/TextInput.js.snap
Restore correct styling to text input component
=> Restore correct styles to text input

CHANGELOG.md, package.json
=> bump-version-2.3.2

CHANGELOG.md, package-lock.json, package.json, src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap, src/Field/Field.tsx, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/TextInput/__tests__/__snapshots__/TextInput.js.snap, src/Textarea/__tests__/__snapshots__/Textarea.js.snap
Fix for search inputs fixing across sign up. When running yalc this example is fixed:
- Adds `width: 100%` to Field component
- Updates `CHANGELOG` and snapshots
=> Updates width of field

src/Fieldset/Fieldset.tsx
One liner updating the the type of `children` in the new fieldset component
=> update type of children in fieldset component

src/Datepicker/Datepicker.tsx, src/Datepicker/DatesList.tsx
=> Datepicker - Shift day by default

CHANGELOG.md, src/SupportMessage/SupportMessage.tsx, src/utils/space.tsx
=> Improve spacing props

CHANGELOG.md, src/NumberInput/NumberInput.tsx, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/TextInput/TextInput.tsx, src/TextInput/__tests__/__snapshots__/TextInput.js.snap
If you don't mind checking out the branch and test it might be a good thing cause it has **A LOT** of edge cases 😢
=> Migrate NumberInput to use Field component

src/Field/Field.tsx, src/SupportMessage/SupportMessage.tsx, src/Textarea/Textarea.stories.tsx
- Update Field component title with correct tag and styles
- Add storybook example for rendering label as title
- Add htmlFor prop linked to input field
=> Field component updates

package-lock.json, package.json
- Tag was pushed but not updated in package.json
- This PR updates package.json without pushing the new tag so that the actual tag and the package version are in sync
=> Fix out of sync tag and install update

CHANGELOG.md, package-lock.json, package.json, src/ConfirmationRadioButtons/Confirmation.stories.tsx, src/ConfirmationRadioButtons/Confirmation.tsx, src/ConfirmationRadioButtons/RadioButtonStyled.tsx, src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap
=> Add disabled state to Confirmation component

src/Accordion/Accordion.tsx
- **Closed state**
- **Opened state**
- **Closed state**
- **Opened state**
- **Closed state**
- **Opened state**
- **Closed state**
- **Opened state**
Improve touchable area of Accordion
=> Update interactive area of Accordion

CHANGELOG.md, src/Accordion/Accordion.tsx
Will be mostly used for analytic purpose (track event when opening accordion) but could be used later on to have a controlled Accordion when we see the need
=> Add `onToggle` prop to Accordion

CHANGELOG.md, src/ConfirmationRadioButtons/Confirmation.tsx, src/ConfirmationRadioButtons/RadioButtonStyled.tsx, src/Dropdown/Dropdown.tsx, src/NumberInput/NumberInput.tsx, src/SearchInput/SearchInput.tsx, src/Text/README.md, src/TextInput/TextInput.tsx, src/Textarea/Textarea.tsx
=> Add OnBlur to SearchInput

CHANGELOG.md, src/Text/Text.tsx
=> make `tag` prop optional on `Text`

src/Dropdown/Dropdown.stories.tsx, src/Dropdown/Dropdown.tsx, src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap, src/Field/Field.tsx, src/Fieldset/Fieldset.tsx, src/NumberInput/NumberInput.tsx, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/SearchInput/SearchInput.tsx, src/SearchInput/__tests__/__snapshots__/SearchInput.js.snap, src/TextInput/TextInput.tsx, src/TextInput/__tests__/__snapshots__/TextInput.js.snap, src/Textarea/Textarea.tsx, src/Textarea/__tests__/__snapshots__/Textarea.js.snap
No UI changes but cleaned up some of the props that were doing nothing
=> Clean Field component

CHANGELOG.md, src/RadioGroup/types.ts
=> Add `null` as a possible value for `RadioGroup`

CHANGELOG.md, src/RadioGroup/RadioItem.tsx
=> Update `RadioGroup`'s option width for `horizontal-card`

CHANGELOG.md, src/ConfirmationRadioButtons/Confirmation.tsx, src/RadioButton/RadioButton.tsx
=> Add deprecated message for `Confirmation` and `RadioButton`

CHANGELOG.md, src/Dropdown/Dropdown.tsx, src/Dropdown/__tests__/__snapshots__/Dropdown.js.snap, src/NumberInput/NumberInput.tsx, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/SearchInput/SearchInput.tsx, src/TextInput/TextInput.tsx, src/TextInput/__tests__/__snapshots__/TextInput.js.snap, src/Textarea/__tests__/__snapshots__/Textarea.js.snap, src/fields/Field/Field.tsx, src/fields/Fieldset/Fieldset.tsx, src/fields/components/InternalField.tsx
=> Pass `htmlFor` to input and select

CHANGELOG.md
=> Update  changelog for release

CHANGELOG.md, package-lock.json, package.json
=> Fix changelog date and bump release version

CHANGELOG.md, src/Dropdown/Dropdown.tsx
This message is showing up when `value` is provided
=> Fix Dropdown's `defaultValue`/`value` props behaviour

CHANGELOG.md, src/Datepicker/Datepicker.tsx
=> Add type to buttons in datepicker

CHANGELOG.md, src/Datepicker/DatesList.tsx, src/RadioGroup/RadioItem.tsx
- Adds some data id's for selenium tests
=> Adds missing data ids

CHANGELOG.md, package-lock.json, package.json, src/Dropdown/Dropdown.tsx
- Allows `value` prop to be `null`
- Updates `CHANGELOG`
=> Adds value prop as null

CHANGELOG.md, package-lock.json, package.json
=> Release prep

CHANGELOG.md, src/CheckBox/CheckBox.tsx, src/RadioGroup/RadioElement.tsx, src/RadioGroup/RadioGroup.tsx, src/RadioGroup/RadioItem.tsx, src/SearchInput/SearchInput.tsx
=> Add `ref` to `CheckBox`, `RadioGroup` and `SearchInput`

CHANGELOG.md, src/RadioGroup/RadioElement.tsx, src/RadioGroup/RadioGroup.tsx
=> Fix `RadioGroup` ref

CHANGELOG.md, src/Datepicker/Datepicker.tsx
=> Make `DatePicker` controllable

CHANGELOG.md, src/Icon/Container.tsx, src/Icon/Icon.tsx
=> add open and close panel icons

CHANGELOG.md, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap, src/utils/flex.tsx, src/utils/space.tsx
=> Add `gap`, `columnGap` and `rowGap` prop to `Box`

CHANGELOG.md, package-lock.json, src/Box/Box.stories.tsx, src/Box/__tests__/__snapshots__/Box.js.snap, src/ConfirmationRadioButtons/__tests__/__snapshots__/Confirmation.js.snap, src/Modal/__tests__/__snapshots__/Modal.js.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/Pagination/__tests__/__snapshots__/Pagination.js.snap, src/RadioButton/__tests__/__snapshots__/RadioButton.js.snap, src/utils/flex.tsx, src/utils/responsiveProp.ts, src/utils/space.tsx
=> Add Responsive props

package-lock.json, package.json
=> chore(version): bump to v2.17.0

package-lock.json, package.json
=> chore(version): bump to v2.17.1

CHANGELOG.md, package-lock.json, package.json, src/Modal/Modal.stories.tsx, src/Modal/Modal.tsx
- Wrap modal in portal to properly centre in all cases
=> properly centre modal

CHANGELOG.md, package-lock.json, package.json, src/Modal/Modal.stories.tsx, src/Modal/Modal.tsx, src/Modal/useBodyScrollLock.ts
Prevent page behind modals to be scrolled while modal is open
=> Add body scroll lock to modals

CHANGELOG.md, src/Modal/Modal.tsx
https://user-images.githubusercontent.com/1053476/222508540-01fb0f64-4a6d-4e90-9e75-3354cb0e9857.mov
- add new show/hide animation for Modal component
=> Modal animation

CHANGELOG.md, src/Modal/Modal.tsx
Reverts marshmallow-insurance/smores-react#2559
=> Revert "Modal animation"

package-lock.json, package.json
=> bump version to 2.18.1

package-lock.json, package.json
Bumpity bump (I will automate this one day)
=> bump to v2.18.5

package-lock.json, package.json
=> chore(version): bump to 2.19.1

package-lock.json, package.json
=> chore(version): bump v2.19.3

src/Chip/Chip.tsx
Updates the Chip colours in line with the rebrand
FE RFC [here](https://www.notion.so/getmarshmallow/Chips-fb27f6a1cc3745eb86f535585e2791d2)
Figma [here](https://www.figma.com/file/FqSaizGOyOzXFZNmZ4X0LGMn/branch/QtMe0nsVPpPkgqtdqd2Op2/%F0%9F%8D%AC-S'mores?type=design&node-id=14402-144873&mode=design&t=BkWEhFv6Na0n7afS-0)
=> Update Chip colours

CHANGELOG.md, src/Accordion/Accordion.tsx, src/CheckBox/CheckBox.tsx, src/CheckBox/__tests__/__snapshots__/CheckBox.js.snap, src/Tag/Tag.tsx, src/Tag/__tests__/__snapshots__/Tag.js.snap, src/Text/README.md, src/Text/Text.stories.tsx, src/Text/Text.tsx, src/Text/fontMapping.ts
N/A
- sets `Tag` component to have fixed height
- adjusts `Checkbox` border to have 2px border
- adds heading-alternate style to `Text`
- adds backgroundColor and borderColor to `Accordion`
=> fix: general rebrand fixes v2

.storybook/main.ts, package-lock.json, package.json, src/CheckBox/index.ts, src/Link/index.ts, src/fields/Field/index.ts, src/fields/Fieldset/index.ts
N/A
- addresses build issue in preview
- fixes random typeErrors caused by prop exports in index.ts files
=> vite preview & typeErrors fixes

.github/workflows/build_and_deploy.yml, package.json
N/A
- https://github.com/storybookjs/storybook/issues/21711
=> adding jekyll: false to workflow

.github/workflows/build_and_deploy.yml, .storybook/main.ts, package-lock.json, package.json
N/A
- reverting unneeded changes that i merged, in an attempt to fix the `gh-pages` build error
- also contains the creations of the `.nojekyll` file, which fixes the build error (the `@storybook/react-vite` bundler creates a file beginning with '_' which was getting ignored, the `.nojekyll` file fixes this)
=> chore: reverting unneeded build fix attempts

CHANGELOG.md, package-lock.json, package.json, src/TextInput/TextInput.tsx
Add tel type to TextField input type
=> Chore add tel type to text input types

CHANGELOG.md, package-lock.json, package.json, src/CheckBox/index.ts, src/Link/index.ts, src/fields/Field/index.ts, src/fields/Fieldset/index.ts
N/A
- re-exports props that were removed
=> fix: re-exporting props

CHANGELOG.md, babel.config.js, babel.config.json, jest.config.js, package-lock.json, package.json
N/A
- reverts jest-config & babel-config back to modules
=> fix: revert jest-config & babel-config back to modules

src/MarshformGenerator/EmotionWrapper.tsx, src/MarshformGenerator/MarshformGenerator.tsx, src/MarshformGenerator/MarshformWrapper.tsx
=> fix eye positioning and sizing

src/MarshformGenerator/MarshformGenerator.stories.tsx, src/MarshformGenerator/MarshformGenerator.tsx
=> Dedupe selected colours from random

.github/workflows/autoApproveDependabotPullRequests.yml
Updates the `autoApproveDependabotPullRequests` workflow is also updated to use the latest version of the `dependabot/fetch-metadata` and `hmarr/auto-approve-action` steps.
=> Upgrade dependabot/fetch-metadata and auto-approve-action action steps

README.md
Reverts marshmallow-insurance/smores-react#3231
=> Revert "fix: deleting some readme"

README.md
=> fix: temp deleting part of readme

.releaserc, README.md, package-lock.json, package.json
=> fix: undo changelog delete

package-lock.json, package.json
N/A
- bumps version so semantic-releases picks up correct version tag
=> fix: version bump to fix CHANGELOG order

.releaserc
N/A
- adds repositoryUrl to` .releaserc`
=> fix: add repositoryUrl to releaserc

.github/workflows/bump_and_publish.yml
N/A
- possible fix from : https://github.com/semantic-release/semantic-release/issues/2481
=> chore: adjust contents permissions to write in workflow

.github/workflows/bump_and_publish.yml, .releaserc
=> fix: adjusting repository url

src/Dropdown/Collection.tsx, src/Dropdown/Dropdown.tsx, src/NumberInput/__tests__/__snapshots__/NumberInput.js.snap, src/TextInput/Collection.tsx, src/fields/components/CommonInput.tsx
[Demo](https://www.loom.com/share/3d53c24399fc4a6d8e1c105fdb716e2b)
- removes hover state for disabled TextInput and Dropdown
=> Feat dropdown textinput disabled hover state

src/LabelledText/LabelledText.tsx
N/A
- changes prop to optional
=> fix: labelMargin optional

src/NumberInput/Container.tsx, src/NumberInput/NumberInput.tsx, src/NumberInput/__tests__/NumberInput.js
Reverts marshmallow-insurance/smores-react#3467
=> Revert "fix: fix NumberInput for currencies"

package-lock.json, package.json, tsconfig.json
N/A
- adds missed rootDir to tsconfig 
- adds rimraf to purge dist folder before building, for clarity with build and config changes
=> fix: add root-dir

package-lock.json, package.json
- bundle @lexical/react module - this needs ot be bundled as it's not a dev dependancy
=> patch: bundle @lexical/react module - this needs ot be bundled as it's not a dev dependancy

opslevel.yml
PR generated using multi-gitter. See https://github.com/marshmallow-insurance/Platform-multi-git-changes/pull/23 for more details.
=> replace opslevel.yml tags with custom properties [skip ci]

opslevel.yml
=> fix opslevel.yml repository name

opslevel.yml
=> chore: add ops level tier

src/Table/storybook/storyUtils.tsx
Just add a table story util name change to have the release commit
=> fix(storyUtils): to have release pr

release.config.js
N/A
- converts the release.config to use module.exports
=> chore: fix release config to use module.exports

src/Accordion/__tests__/__snapshots__/Accordion.spec.tsx.snap, src/ActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.tsx.snap, src/BrandCard/__tests__/__snapshots__/BrandCard.spec.tsx.snap, src/Button/__tests__/__snapshots__/Button.spec.tsx.snap, src/Card/__tests__/__snapshots__/Card.spec.tsx.snap, src/CheckBox/__tests__/__snapshots__/CheckBox.spec.tsx.snap, src/CurrencyInput/__tests__/__snapshots__/CurrencyInput.spec.tsx.snap, src/Icon/__tests__/__snapshots__/Icon.spec.tsx.snap, src/Icon/iconFiles/CaretUp.tsx, src/Icon/iconsList.ts, src/IconStrict/__tests__/__snapshots__/IconStrict.spec.tsx.snap, src/IconWrapper/__tests__/__snapshots__/IconWrapper.spec.tsx.snap, src/LabelledText/__tests__/__snapshots__/LabelledText.spec.tsx.snap, src/NumberInput/__tests__/__snapshots__/NumberInput.spec.tsx.snap, src/Pagination/__tests__/__snapshots__/Pagination.spec.tsx.snap, src/Row/__tests__/__snapshots__/Row.spec.tsx.snap, src/Tag/__tests__/__snapshots__/Tag.spec.tsx.snap, src/Text/__tests__/__snapshots__/Text.spec.tsx.snap, src/TextInput/__tests__/__snapshots__/TextInput.spec.tsx.snap
=> Feat: Add caret-up icon

README.md, release.config.js
Added a change to readme and managing a failed released due to issue with casing of semantic release keywords.
=> chore: update readme

src/Datepicker/Datepicker.tsx, src/Datepicker/storybook/Datepicker.stories.tsx
- Allow datepicker to be completely disabled
=> feat: add optional  `disabled` prop to `Datepicker`

src/Badge/Badge.tsx, src/BadgeList/BadgeList.stories.tsx, src/BadgeList/BadgeList.tsx
https://github.com/marshmallow-insurance/smores-react/assets/63399235/b5b708a2-0554-46b4-8c1d-4f0afa07f8e3
- Add optional `size` to BadgeList
-  Improve `BadgeList` hover animation, badges will now expand respective to where they are in the list, instead of all badges expanding (improving on issues with limited real estate)
- [Allow Badge to take JSX instead of a url](https://github.com/marshmallow-insurance/smores-react/pull/3809/commits/39ad4da9c467a4f6e639748fcb31466cfd36e326)
- [Add limit prop, truncating list when pass limit](https://github.com/marshmallow-insurance/smores-react/pull/3809/commits/16ae5a870ffc4e23cacc8b66cf5dcd3d3c850255)
- Badge: Use `border` instead of `outline`
- [Squash BadgeList more](https://github.com/marshmallow-insurance/smores-react/pull/3809/commits/3bdd8655 …
=> feat: Improve badge list and badge

.github/dependabot.yml
PR generated using multi-gitter. 
This PR updates the dependabot commit messages and PR titles to be more aligned with our conventional commit standards. for more details please see [this RFC](https://www.notion.so/getmarshmallow/Dependabot-PR-titles-3439f318a9b943e0af938fe7fac1f0d7?pvs=4)
=> feat(core): Dependabot commit & PR titles - [🤖 generated]

.github/dependabot.yml
PR generated using multi-gitter. 
This PR fixes the double "scope" created by dependabot PRs after the following [RFC change](https://www.notion.so/getmarshmallow/Dependabot-PR-titles-3439f318a9b943e0af938fe7fac1f0d7?pvs=4)
=> fix(core): Dependabot PR titles - [🤖 generated]

src/Icon/iconFiles/Reply.tsx, src/Icon/iconsList.ts
Adding new reply icon 
Ned to have CMS coms v2
check in smore's
=> feat(icon): reply icon

src/Icon/iconFiles/Progress.tsx, src/Icon/iconsList.ts
=> feat(iconList): add progress

src/ActionDropdown/ActionDropdown.tsx, vitest.config.ts
- Removes the overflow from the `SelectedOption` in the `ActionDropdown` to prevent the text from being cut off
- Adds `dist` folder to the ignored test files in `vitest.config`
=> chore(action dropdown component): update overflow and border radius

src/utils/dateOfBirth/dateOfBirthValidator.utils.ts
- Fix missing import issue found when consuming library
Didn't catch this one in the [previous PR](https://github.com/marshmallow-insurance/smores-react/pull/4170)
=> fix(library): Missing import

src/Text/Text.tsx, src/Text/storybook/Text.stories.tsx
=> Feat remove deprecated typos

src/Tag/Tag.spec.tsx, src/Tag/Tag.tsx, vitest.config.ts
Adds test for Tag component
[Tag component](http://localhost:6006/?path=/story/tag--with-icon)
[Tastk](https://marshmallow1.atlassian.net/browse/CLM-872)
Unit tests added for Tag component
src/Tag/Tag.spec.tsx
=> test(tag): added test for tag component

src/Icon/Icon.tsx, src/SegmentedControl/ToggleButton.tsx
Changing the usage of test id from `data-testId` to data-testid` so it's correct and usalbe within vitest.
N/A
N/A
N/A
=> chore: fix testid on components

src/fields/components/InternalField.tsx
Adds warning icon to required text as per design system - https://www.figma.com/design/FqSaizGOyOzXFZNmZ4X0LGMn/%F0%9F%8D%AC-S-mores?node-id=12474-90520&m=dev
=> chore: adding warning icon to required text

src/CheckBox/CheckBox.tsx
This pull request includes updates to the `CheckBox` component's styling in `src/CheckBox/CheckBox.tsx`. The changes focus on improving layout consistency by adjusting dimensions and spacing.
Styling improvements:
* Added a `min-height` of 24px to the `BoxContainer` to ensure consistent vertical spacing for the checkbox label.
* Updated the `span` element inside `BoxContainer` to include a `line-height` of 24px for better alignment of text within the checkbox.
* Replaced `ErrorBox` from a `span` to a `div`, changed `padding-top` to `margin-top` with a value of 4px, and retained the error styling for improved spacing and semantics.
**Before:**
**After:**
=> fix(checkbox): adjust BoxContainer and ErrorBox styles for better layout

src/Dropdown/Dropdown.tsx
Fixes bug where dropdown was switched to controlled
=> feat(dropdown): fix dropdown controlled to uncontrolled

src/colors.stories.tsx, src/theme.ts
Adds a new color called satsuma
https://marshmallow1.atlassian.net/browse/CLM-1516
=> feat(color): added new color

.github/dependabot.yml
group them up to reduce the maintenance burden
=> chore(dependabot): add storybook group for dependency updates

package-lock.json, package.json
- Upgrades typescript to the latest version
- Upgrades typescript eslint to the latest version
N/A
N/A
- Unit tests still pass
=> chore(npm): upgrade typescript & typescript eslint

src/ProgressIndicator/ProgressIndicator.tsx, src/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap, src/ProgressIndicator/components/StepItem.test.tsx, src/ProgressIndicator/components/StepItem.tsx, src/ProgressIndicator/components/__snapshots__/StepItem.test.tsx.snap
- Uses theme provider colours for progress indicator
> [!NOTE]
> Design have okayed the colour change 🎉  
https://github.com/user-attachments/assets/157497ec-1942-42f5-a998-f30a08ff40a0
N/A
- snapshot tests added
- snapshot tests updated
=> feat(progress-indicator): align with design system [DES-67]

src/RadioGroup/RadioElement.tsx, src/RadioGroup/RadioItem.tsx, src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- Updates `RadioGroup` to use the theme provider colours
https://github.com/user-attachments/assets/6ec0e1f2-aeda-47cb-85c2-63ad09b68fe1
N/A
- snapshot tests updated
=> chore(radio-group): update to use theme provider [DES-68]

src/RichTextEditor/RichTextEditor.tsx, src/RichTextEditor/plugins/ToolbarPlugin.tsx
- Update rich text editor to use new colours
https://github.com/user-attachments/assets/b6ffa06b-7324-4bc9-b7a2-75f82ef69f92
N/A
- N/A
=> feat(rich-text-editor): update theming [DES-70]

src/SearchInput/SearchInput.tsx, src/SearchInput/components/SearchOptions.tsx
- Update `SearchInput` to use theme provided colours
https://github.com/user-attachments/assets/2ff4fd3c-7f6c-4b99-8587-52a3f4114a13
N/A
N/A
=> chore(search-input): update to use theme provider [DES-72]

src/SliderInput/SliderInput.tsx, src/SliderInput/__snapshots__/SliderInput.test.tsx.snap
- Updates the slider component to use the theme provider
https://github.com/user-attachments/assets/e11d0781-f1bd-4828-8c77-8940350eb95e
N/A
- Snapshots updated
=> chore(slider): update to use theme provider [DES-74]

src/Textarea/Textarea.test.tsx, src/Textarea/Textarea.tsx, src/Textarea/__snapshots__/Textarea.test.tsx.snap
- Updates `Textarea` to use theme provided colours
https://github.com/user-attachments/assets/cb87704a-6726-4802-9817-28c7059ae898
N/A
- unit tests added
- snapshot test added
=> chore(textarea): update to use theme provider [DES-82]
